-- ============================================================
-- 02_tables.sql
-- All public tables with PK + column defaults (no FKs/UQ/CHECK yet)
-- ============================================================

CREATE TABLE public.admin_agent_messages (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  direction text NOT NULL,
  message_type text NOT NULL,
  alert_kind text,
  reference_id uuid,
  content text NOT NULL,
  whatsapp_message_id text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.admin_notifications (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  created_by uuid,
  type notification_type DEFAULT 'system'::notification_type,
  title text NOT NULL,
  message text,
  action_url text,
  scope text DEFAULT 'all'::text NOT NULL,
  scope_filters jsonb DEFAULT '{}'::jsonb,
  send_app boolean DEFAULT true,
  send_email boolean DEFAULT false,
  recipients_count integer DEFAULT 0,
  emails_sent integer DEFAULT 0,
  emails_failed integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  sent_at timestamp with time zone,
  PRIMARY KEY (id)
);
CREATE TABLE public.agent_action_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  conversation_id uuid,
  product_id uuid,
  agent_id uuid,
  lead_id uuid,
  action_type character varying(100) NOT NULL,
  action_data jsonb DEFAULT '{}'::jsonb,
  result jsonb DEFAULT '{}'::jsonb,
  success boolean DEFAULT true NOT NULL,
  error_message text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.agent_activation_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid,
  conversation_id uuid,
  lead_id uuid,
  from_agent_id uuid,
  to_agent_id uuid,
  matched_term text,
  match_type text,
  channel text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.agent_handoff_history (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  conversation_id uuid,
  lead_id uuid,
  from_agent_id uuid,
  to_agent_id uuid,
  to_specialist_id uuid,
  reason text,
  rule_id uuid,
  context jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.agent_post_sale_scenarios (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  trigger_event text NOT NULL,
  priority integer DEFAULT 0 NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  instruction text NOT NULL,
  links jsonb DEFAULT '[]'::jsonb NOT NULL,
  tags_to_apply text[] DEFAULT '{}'::text[] NOT NULL,
  filters jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  created_by uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.agent_routing_rules (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true NOT NULL,
  priority integer DEFAULT 100 NOT NULL,
  match_stage_ids uuid[],
  match_tag_ids uuid[],
  match_product_ids uuid[],
  match_channels text[],
  match_events text[],
  deal_value_min numeric,
  deal_value_max numeric,
  target_specialist_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  match_count integer DEFAULT 0 NOT NULL,
  last_matched_at timestamp with time zone,
  PRIMARY KEY (id)
);
CREATE TABLE public.agent_safety_limits (
  organization_id uuid NOT NULL,
  max_tools_per_turn integer DEFAULT 5 NOT NULL,
  max_tool_executions_per_day integer DEFAULT 5000 NOT NULL,
  max_cost_cents_per_day integer DEFAULT 50000 NOT NULL,
  cooldown_seconds_between_same_tool integer DEFAULT 2 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (organization_id)
);
CREATE TABLE public.agent_specialists (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  role text NOT NULL,
  display_name text NOT NULL,
  description text,
  is_active boolean DEFAULT true NOT NULL,
  priority integer DEFAULT 100 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.agent_tool_executions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  agent_id uuid,
  agent_name text,
  lead_id uuid,
  conversation_id uuid,
  channel text,
  tool_name text NOT NULL,
  input jsonb DEFAULT '{}'::jsonb NOT NULL,
  output jsonb,
  success boolean DEFAULT true NOT NULL,
  error_message text,
  duration_ms integer,
  estimated_cost_cents integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.agent_training_materials (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  title text NOT NULL,
  material_type text NOT NULL,
  category text DEFAULT 'general'::text NOT NULL,
  description text,
  file_url text,
  extracted_content text,
  is_active boolean DEFAULT true,
  processing_status text DEFAULT 'pending'::text,
  processing_error text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  product_id uuid,
  agent_id uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.ai_audits (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  interaction_id uuid NOT NULL,
  quality_score integer,
  issues text[] DEFAULT '{}'::text[],
  suggestions text[] DEFAULT '{}'::text[],
  tone_analysis jsonb DEFAULT '{}'::jsonb,
  analyzed_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.ai_insights (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid,
  product_id uuid,
  organization_id uuid,
  type text NOT NULL,
  title text NOT NULL,
  insight text NOT NULL,
  priority task_priority DEFAULT 'medium'::task_priority,
  is_dismissed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.ai_knowledge_base (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  category text DEFAULT 'general'::text NOT NULL,
  tags text[] DEFAULT '{}'::text[],
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.ai_outreach_queue (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  lead_id uuid NOT NULL,
  conversation_id uuid,
  product_id uuid,
  agent_id uuid,
  webhook_id uuid,
  objective text,
  extra_context text,
  lead_data jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'pending'::text NOT NULL,
  followup_enabled boolean DEFAULT false NOT NULL,
  followup_interval_hours integer DEFAULT 24,
  max_followups integer DEFAULT 3,
  followups_sent integer DEFAULT 0 NOT NULL,
  last_outreach_at timestamp with time zone,
  next_followup_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  followup_steps jsonb DEFAULT '[]'::jsonb,
  business_hours_start text DEFAULT '09:00'::text,
  business_hours_end text DEFAULT '18:00'::text,
  business_days integer[] DEFAULT '{1,2,3,4,5}'::integer[],
  PRIMARY KEY (id)
);
CREATE TABLE public.ai_prompt_experiments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  agent_id uuid,
  status text DEFAULT 'draft'::text NOT NULL,
  primary_metric text DEFAULT 'score_overall'::text,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.ai_prompt_variants (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  experiment_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  label text NOT NULL,
  prompt_override text,
  prompt_mode text DEFAULT 'append'::text NOT NULL,
  weight integer DEFAULT 50 NOT NULL,
  impressions integer DEFAULT 0 NOT NULL,
  conversions integer DEFAULT 0 NOT NULL,
  total_score numeric DEFAULT 0 NOT NULL,
  evaluations_count integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.ai_quality_evaluations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  conversation_id uuid,
  agent_id uuid,
  lead_id uuid,
  evaluated_messages_count integer DEFAULT 0,
  score_overall numeric,
  score_clarity numeric,
  score_tone numeric,
  score_objectivity numeric,
  score_accuracy numeric,
  score_conversion_potential numeric,
  detected_objections jsonb DEFAULT '[]'::jsonb,
  detected_intents jsonb DEFAULT '[]'::jsonb,
  detected_issues jsonb DEFAULT '[]'::jsonb,
  summary text,
  improvement_suggestions text,
  judge_model text,
  cost_usd numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.ai_response_feedback (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  message_id uuid,
  conversation_id uuid,
  original_response text NOT NULL,
  suggested_response text NOT NULL,
  feedback_type text DEFAULT 'correction'::text,
  created_by uuid,
  organization_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  applied_to_training boolean DEFAULT false,
  applied_at timestamp with time zone,
  PRIMARY KEY (id)
);
CREATE TABLE public.ai_router_failures (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  capability text NOT NULL,
  provider text NOT NULL,
  status_code integer,
  error_message text,
  fell_back_to text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.auto_notification_settings (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  stalled_lead_enabled boolean DEFAULT true,
  stalled_lead_days integer DEFAULT 3,
  goal_achieved_enabled boolean DEFAULT true,
  commission_approved_enabled boolean DEFAULT true,
  daily_report_enabled boolean DEFAULT true,
  daily_report_hour integer DEFAULT 7,
  daily_report_send_email boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  admin_agent_enabled boolean DEFAULT false,
  admin_whatsapp_number text,
  admin_user_id uuid,
  daily_summary_enabled boolean DEFAULT true,
  daily_summary_hour integer DEFAULT 8,
  weekly_report_enabled boolean DEFAULT true,
  weekly_report_dow integer DEFAULT 1,
  weekly_report_hour integer DEFAULT 8,
  realtime_alerts_enabled boolean DEFAULT true,
  alert_high_value_threshold numeric DEFAULT 10000,
  alert_unattended_minutes integer DEFAULT 15,
  alert_offline_minutes integer DEFAULT 30,
  alert_agent_error_threshold integer DEFAULT 3,
  alert_meeting_changes boolean DEFAULT true,
  alert_goal_achieved boolean DEFAULT true,
  monitored_product_ids uuid[],
  summary_kpis text[] DEFAULT ARRAY['leads_created'::text, 'conversions'::text, 'pipeline_total'::text, 'meetings'::text, 'overdue_tasks'::text, 'top_sellers'::text],
  weekly_include_comparison boolean DEFAULT true,
  alert_product_volume_spike boolean DEFAULT false,
  alert_product_volume_spike_pct integer DEFAULT 50,
  alert_critical_product_idle_hours integer DEFAULT 24,
  PRIMARY KEY (id)
);
CREATE TABLE public.availability_overrides (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  date date NOT NULL,
  is_available boolean DEFAULT false,
  start_time time without time zone,
  end_time time without time zone,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.billing_history (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid,
  subscription_id uuid,
  amount numeric(10,2) NOT NULL,
  status text DEFAULT 'pending'::text,
  invoice_url text,
  payment_date timestamp with time zone,
  due_date timestamp with time zone,
  description text,
  stripe_invoice_id text,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.booking_event_types (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  duration_minutes integer DEFAULT 30 NOT NULL,
  location_type text DEFAULT 'google_meet'::text NOT NULL,
  location_details text,
  color text DEFAULT '#3b82f6'::text,
  is_active boolean DEFAULT false,
  buffer_before integer DEFAULT 0,
  buffer_after integer DEFAULT 0,
  min_notice_hours integer DEFAULT 24,
  max_days_ahead integer DEFAULT 60,
  questions jsonb DEFAULT '[]'::jsonb,
  confirmation_message text,
  create_meet boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  thank_you_title text,
  thank_you_message text,
  what_happens jsonb DEFAULT '[]'::jsonb,
  next_steps jsonb DEFAULT '[]'::jsonb,
  booking_experience text DEFAULT 'standard'::text,
  PRIMARY KEY (id)
);
CREATE TABLE public.booking_requests (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  event_type_id uuid NOT NULL,
  host_user_id uuid NOT NULL,
  calendar_event_id uuid,
  guest_name text NOT NULL,
  guest_email text NOT NULL,
  guest_phone text,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  timezone text DEFAULT 'America/Sao_Paulo'::text,
  status text DEFAULT 'confirmed'::text,
  additional_info jsonb DEFAULT '{}'::jsonb,
  cancellation_reason text,
  confirmation_token text DEFAULT encode(extensions.gen_random_bytes(16), 'hex'::text),
  lead_id uuid,
  tracking jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.business_holidays (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  date date NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.business_hours (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  timezone text DEFAULT 'America/Sao_Paulo'::text NOT NULL,
  schedule jsonb DEFAULT jsonb_build_object('mon', jsonb_build_array(jsonb_build_object('start', '09:00', 'end', '18:00')), 'tue', jsonb_build_array(jsonb_build_object('start', '09:00', 'end', '18:00')), 'wed', jsonb_build_array(jsonb_build_object('start', '09:00', 'end', '18:00')), 'thu', jsonb_build_array(jsonb_build_object('start', '09:00', 'end', '18:00')), 'fri', jsonb_build_array(jsonb_build_object('start', '09:00', 'end', '18:00')), 'sat', jsonb_build_array(), 'sun', jsonb_build_array()) NOT NULL,
  out_of_hours_message text DEFAULT 'Olá! No momento estamos fora do horário de atendimento. Retornaremos em breve.'::text NOT NULL,
  out_of_hours_enabled boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.cadence_templates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid NOT NULL,
  day_number integer NOT NULL,
  title text NOT NULL,
  trigger text,
  blocks jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.cakto_credentials (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  scope text NOT NULL,
  organization_id uuid,
  client_id text NOT NULL,
  client_secret text NOT NULL,
  scopes text[] DEFAULT ARRAY['read'::text, 'orders'::text, 'products'::text] NOT NULL,
  webhook_secret text,
  last_token text,
  token_expires_at timestamp with time zone,
  connection_status text DEFAULT 'disconnected'::text NOT NULL,
  last_sync_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.cakto_orders (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  scope text NOT NULL,
  organization_id uuid,
  cakto_id text NOT NULL,
  cakto_ref_id text,
  status text NOT NULL,
  type text,
  offer_type text,
  payment_method text,
  base_amount numeric(12,2),
  discount numeric(12,2),
  amount numeric(12,2),
  coupon_code text,
  customer_name text,
  customer_email text,
  customer_phone text,
  customer_document text,
  product_cakto_id text,
  product_name text,
  product_image text,
  paid_at timestamp with time zone,
  created_at_cakto timestamp with time zone,
  raw_payload jsonb,
  synced_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  product_id uuid,
  offer_id uuid,
  items jsonb DEFAULT '[]'::jsonb,
  provider text DEFAULT 'cakto'::text NOT NULL,
  assigned_to uuid,
  lead_id uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.cakto_recovery_config (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  is_enabled boolean DEFAULT false NOT NULL,
  recovery_agent_id uuid,
  trigger_on_abandoned boolean DEFAULT true NOT NULL,
  trigger_on_paid boolean DEFAULT true NOT NULL,
  trigger_on_refunded boolean DEFAULT false NOT NULL,
  delay_seconds integer DEFAULT 0 NOT NULL,
  cooldown_minutes integer DEFAULT 60 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.cakto_recovery_dispatches (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  cakto_order_id uuid,
  cakto_event text NOT NULL,
  cakto_status text,
  lead_id uuid,
  agent_id uuid,
  conversation_id uuid,
  customer_phone text,
  customer_email text,
  message_sent text,
  success boolean DEFAULT false NOT NULL,
  error_message text,
  skipped_reason text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.calendar_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  location text,
  event_type text DEFAULT 'meeting'::text,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  all_day boolean DEFAULT false,
  timezone text DEFAULT 'America/Sao_Paulo'::text,
  is_recurring boolean DEFAULT false,
  recurrence_rule text,
  recurrence_end_date date,
  parent_event_id uuid,
  lead_id uuid,
  product_id uuid,
  deal_id uuid,
  attendees jsonb DEFAULT '[]'::jsonb,
  status text DEFAULT 'confirmed'::text,
  reminder_minutes integer[] DEFAULT ARRAY[15, 60],
  google_event_id text,
  google_calendar_id text,
  last_synced_at timestamp with time zone,
  sync_status text DEFAULT 'local_only'::text,
  color text,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  synced_from_google boolean DEFAULT false,
  meet_link text,
  create_meet boolean DEFAULT false,
  PRIMARY KEY (id)
);
CREATE TABLE public.capture_funnels (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  slug text NOT NULL,
  status text DEFAULT 'draft'::text NOT NULL,
  flow_blocks jsonb DEFAULT '[]'::jsonb NOT NULL,
  start_block_id text,
  channels jsonb DEFAULT '{"chat": {"enabled": false, "slug_override": null}, "form": {"enabled": false, "slug_override": null}, "widget": {"enabled": false}}'::jsonb NOT NULL,
  widget_config jsonb DEFAULT '{"greeting": "Ola! Como posso ajudar?", "position": "bottom-right", "avatar_url": null, "primary_color": "#3B82F6", "allowed_domains": []}'::jsonb,
  distribution_rule text DEFAULT 'manual'::text NOT NULL,
  assigned_squad_id uuid,
  assigned_user_id uuid,
  round_robin_config jsonb DEFAULT '{"users": [], "current_index": 0}'::jsonb,
  default_temperature text DEFAULT 'warm'::text,
  default_tags text[] DEFAULT '{}'::text[],
  facebook_pixel_id text,
  google_tag_id text,
  custom_scripts jsonb DEFAULT '{"footer": "", "header": ""}'::jsonb,
  utm_capture boolean DEFAULT true,
  theme jsonb DEFAULT '{"logo_url": null, "text_color": "#FFFFFF", "font_family": "Inter", "primary_color": "#3B82F6", "show_progress": true, "background_color": "#0F172A"}'::jsonb,
  ai_enabled boolean DEFAULT true,
  ai_context text,
  total_views integer DEFAULT 0,
  total_leads integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.catalog_sync_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid,
  source_type text DEFAULT 'firecrawl'::text NOT NULL,
  base_url text,
  catalog_type text,
  status text DEFAULT 'running'::text NOT NULL,
  items_found integer DEFAULT 0,
  items_created integer DEFAULT 0,
  items_updated integer DEFAULT 0,
  items_failed integer DEFAULT 0,
  error_message text,
  started_at timestamp with time zone DEFAULT now() NOT NULL,
  finished_at timestamp with time zone,
  created_by uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.chat_flows (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid,
  organization_id uuid NOT NULL,
  name text DEFAULT 'Fluxo de Qualificação'::text NOT NULL,
  description text,
  blocks jsonb DEFAULT '[]'::jsonb NOT NULL,
  start_block_id text,
  is_active boolean DEFAULT true,
  trigger_type text DEFAULT 'always'::text,
  trigger_conditions jsonb DEFAULT '{}'::jsonb,
  collected_variables jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.commission_rules (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid NOT NULL,
  user_id uuid,
  organization_id uuid NOT NULL,
  rule_type text DEFAULT 'percentage'::text NOT NULL,
  base_value numeric DEFAULT 10 NOT NULL,
  min_value numeric DEFAULT 0,
  max_value numeric,
  applies_to text DEFAULT 'deal'::text,
  stage_id uuid,
  is_default boolean DEFAULT true,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.commissions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  deal_id uuid NOT NULL,
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  amount numeric NOT NULL,
  percentage_applied numeric,
  rule_id uuid,
  status text DEFAULT 'pending'::text,
  earned_at timestamp with time zone DEFAULT now(),
  approved_at timestamp with time zone,
  approved_by uuid,
  paid_at timestamp with time zone,
  paid_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.conversation_notes (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.conversation_transfers (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  conversation_id uuid NOT NULL,
  from_user_id uuid,
  to_user_id uuid,
  to_queue_id uuid,
  internal_note text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.custom_fields (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  field_key text NOT NULL,
  field_type text DEFAULT 'text'::text NOT NULL,
  description text,
  options jsonb DEFAULT '[]'::jsonb NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.deals (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lead_id uuid NOT NULL,
  product_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  deal_value numeric NOT NULL,
  status text DEFAULT 'won'::text,
  notes text,
  closed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  plan_name text,
  PRIMARY KEY (id)
);
CREATE TABLE public.distribution_config (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  squad_id uuid,
  method text DEFAULT 'round_robin'::text NOT NULL,
  round_robin_index integer DEFAULT 0 NOT NULL,
  auto_reassign boolean DEFAULT true NOT NULL,
  max_accept_time_minutes integer DEFAULT 5,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.email_send_log (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  message_id text,
  template_name text NOT NULL,
  recipient_email text NOT NULL,
  status text NOT NULL,
  error_message text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.email_send_state (
  id integer DEFAULT 1 NOT NULL,
  retry_after_until timestamp with time zone,
  batch_size integer DEFAULT 10 NOT NULL,
  send_delay_ms integer DEFAULT 200 NOT NULL,
  auth_email_ttl_minutes integer DEFAULT 15 NOT NULL,
  transactional_email_ttl_minutes integer DEFAULT 60 NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.email_templates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  subject text NOT NULL,
  html_content text NOT NULL,
  variables jsonb DEFAULT '[]'::jsonb,
  is_system boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.email_unsubscribe_tokens (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  token text NOT NULL,
  email text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  used_at timestamp with time zone,
  PRIMARY KEY (id)
);
CREATE TABLE public.evolution_instances (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid,
  name text NOT NULL,
  instance_id text,
  instance_token text,
  phone_number text,
  status text DEFAULT 'disconnected'::text NOT NULL,
  qr_code text,
  qr_code_updated_at timestamp with time zone,
  webhook_subscribed boolean DEFAULT false NOT NULL,
  is_default boolean DEFAULT false NOT NULL,
  last_connected_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  created_by_super_admin boolean DEFAULT false NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.facebook_lead_integrations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  page_id text NOT NULL,
  page_name text,
  page_access_token text NOT NULL,
  app_secret text,
  verify_token text NOT NULL,
  field_mapping jsonb DEFAULT '{"email": "email", "full_name": "name", "phone_number": "phone"}'::jsonb,
  distribution_rule text DEFAULT 'manual'::text,
  assigned_user_id uuid,
  assigned_squad_id uuid,
  default_temperature text DEFAULT 'hot'::text,
  default_tags text[] DEFAULT '{}'::text[],
  is_active boolean DEFAULT true,
  last_lead_received_at timestamp with time zone,
  leads_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.facebook_lead_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  integration_id uuid,
  leadgen_id text NOT NULL,
  form_id text,
  ad_id text,
  campaign_id text,
  raw_payload jsonb,
  lead_data jsonb,
  lead_id uuid,
  status text DEFAULT 'pending'::text,
  error_message text,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.form_blocks (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  form_id uuid NOT NULL,
  order_index integer DEFAULT 0 NOT NULL,
  block_type text NOT NULL,
  label text NOT NULL,
  description text,
  placeholder text,
  required boolean DEFAULT false,
  options jsonb DEFAULT '[]'::jsonb,
  logic_rules jsonb DEFAULT '[]'::jsonb,
  maps_to text,
  score_value integer DEFAULT 0,
  score_rules jsonb DEFAULT '[]'::jsonb,
  apply_tags text[] DEFAULT '{}'::text[],
  validation jsonb DEFAULT '{}'::jsonb,
  block_settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.form_submissions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  form_id uuid NOT NULL,
  lead_id uuid,
  responses jsonb DEFAULT '{}'::jsonb NOT NULL,
  total_score integer DEFAULT 0,
  tags text[] DEFAULT '{}'::text[],
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  referrer_url text,
  landing_page text,
  user_agent text,
  ip_address inet,
  geo_country text,
  geo_city text,
  status text DEFAULT 'completed'::text,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  step_analytics jsonb DEFAULT '[]'::jsonb,
  time_spent_seconds integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.form_templates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid,
  name text NOT NULL,
  description text,
  category text DEFAULT 'general'::text,
  thumbnail_url text,
  blocks jsonb DEFAULT '[]'::jsonb NOT NULL,
  theme jsonb DEFAULT '{}'::jsonb,
  settings jsonb DEFAULT '{}'::jsonb,
  is_public boolean DEFAULT false,
  is_system boolean DEFAULT false,
  usage_count integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.forms (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  slug text NOT NULL,
  status text DEFAULT 'draft'::text,
  distribution_rule text DEFAULT 'queue'::text,
  assigned_squad_id uuid,
  assigned_user_id uuid,
  default_temperature text DEFAULT 'warm'::text,
  round_robin_config jsonb DEFAULT '{"users": [], "current_index": 0}'::jsonb,
  theme jsonb DEFAULT '{"logo_url": null, "text_color": "#1f2937", "font_family": "Inter", "button_style": "filled", "redirect_url": null, "border_radius": "8px", "primary_color": "#8B5CF6", "show_progress": true, "secondary_color": "#6366F1", "background_color": "#ffffff"}'::jsonb,
  facebook_pixel_id text,
  google_tag_id text,
  custom_scripts jsonb DEFAULT '{"footer": "", "header": ""}'::jsonb,
  utm_capture boolean DEFAULT true,
  settings jsonb DEFAULT '{"show_branding": true, "auto_create_lead": true, "notify_on_submission": true, "allow_multiple_submissions": false}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  views_count integer DEFAULT 0,
  submissions_count integer DEFAULT 0,
  PRIMARY KEY (id)
);
CREATE TABLE public.funnel_analytics (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  funnel_id uuid NOT NULL,
  channel text NOT NULL,
  date date DEFAULT CURRENT_DATE NOT NULL,
  views integer DEFAULT 0,
  starts integer DEFAULT 0,
  completions integer DEFAULT 0,
  leads_created integer DEFAULT 0,
  PRIMARY KEY (id)
);
CREATE TABLE public.funnel_webhook_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  funnel_id uuid NOT NULL,
  block_id text NOT NULL,
  lead_id uuid,
  organization_id uuid NOT NULL,
  request_url text NOT NULL,
  request_method text DEFAULT 'POST'::text NOT NULL,
  request_headers jsonb DEFAULT '{}'::jsonb,
  request_body jsonb,
  response_status integer,
  response_body text,
  success boolean DEFAULT false NOT NULL,
  error_message text,
  duration_ms integer,
  trigger_source text DEFAULT 'on_block'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.google_calendar_connections (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  calendar_id text DEFAULT 'primary'::text,
  sync_enabled boolean DEFAULT true,
  sync_direction text DEFAULT 'both'::text,
  last_sync_at timestamp with time zone,
  sync_error text,
  connected_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  google_email text,
  is_active boolean DEFAULT true,
  selected_calendar_id text,
  google_event_id text,
  PRIMARY KEY (id)
);
CREATE TABLE public.help_article_feedback (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  article_id uuid NOT NULL,
  user_id uuid NOT NULL,
  is_helpful boolean NOT NULL,
  comment text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.help_articles (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  category_id uuid,
  slug text NOT NULL,
  title text NOT NULL,
  summary text,
  content_json jsonb,
  content_html text,
  cover_image_url text,
  tags text[] DEFAULT '{}'::text[],
  is_published boolean DEFAULT false NOT NULL,
  display_order integer DEFAULT 0 NOT NULL,
  view_count integer DEFAULT 0 NOT NULL,
  helpful_count integer DEFAULT 0 NOT NULL,
  not_helpful_count integer DEFAULT 0 NOT NULL,
  related_release_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  published_at timestamp with time zone,
  PRIMARY KEY (id)
);
CREATE TABLE public.help_categories (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  description text,
  icon text DEFAULT 'BookOpen'::text,
  color text DEFAULT 'primary'::text,
  display_order integer DEFAULT 0 NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  visibility text DEFAULT 'all'::text NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.hotmart_credentials (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  client_id text,
  client_secret text,
  basic_token text,
  hottok text,
  is_active boolean DEFAULT false NOT NULL,
  last_verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.hotmart_orders (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  transaction_id text NOT NULL,
  product_id uuid,
  hotmart_product_id text,
  hotmart_product_name text,
  hotmart_offer_code text,
  buyer_email text,
  buyer_name text,
  buyer_phone text,
  buyer_doc text,
  amount numeric(12,2),
  currency text DEFAULT 'BRL'::text,
  status text NOT NULL,
  event_type text,
  payment_method text,
  installments integer,
  affiliate_email text,
  commission_amount numeric(12,2),
  subscription_code text,
  raw_payload jsonb,
  created_at_hotmart timestamp with time zone,
  synced_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.hotmart_product_mapping (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  hotmart_product_id text NOT NULL,
  hotmart_product_name text,
  product_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.integration_settings (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  integration_type text NOT NULL,
  api_key_masked text,
  is_configured boolean DEFAULT false,
  settings jsonb DEFAULT '{}'::jsonb,
  last_verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.interactions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lead_id uuid NOT NULL,
  user_id uuid,
  channel interaction_channel DEFAULT 'whatsapp'::interaction_channel NOT NULL,
  direction text DEFAULT 'outbound'::text,
  content text NOT NULL,
  cadence_day integer,
  template_used text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.lead_notes (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lead_id uuid NOT NULL,
  author_id uuid NOT NULL,
  content text NOT NULL,
  role_label text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.lead_queue (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lead_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  squad_id uuid,
  product_id uuid,
  priority integer DEFAULT 0 NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  queued_at timestamp with time zone DEFAULT now() NOT NULL,
  assigned_at timestamp with time zone,
  assigned_to uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.lead_semantic_memory (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lead_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  conversation_id uuid,
  message_id uuid,
  source text DEFAULT 'message'::text NOT NULL,
  role text,
  content text NOT NULL,
  embedding vector(1536),
  importance_score numeric DEFAULT 0.5,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.lead_stage_history (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lead_id uuid NOT NULL,
  stage_id uuid,
  entered_at timestamp with time zone DEFAULT now() NOT NULL,
  exited_at timestamp with time zone,
  days_in_stage integer,
  PRIMARY KEY (id)
);
CREATE TABLE public.lead_tag_assignments (
  lead_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  applied_by uuid,
  source text DEFAULT 'manual'::text NOT NULL,
  applied_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (lead_id, tag_id)
);
CREATE TABLE public.lead_tags (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  color text DEFAULT '#6366f1'::text NOT NULL,
  description text,
  is_automatic boolean DEFAULT false NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  is_lifecycle_status boolean DEFAULT false NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.lead_transfer_history (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lead_id uuid NOT NULL,
  from_user_id uuid,
  to_user_id uuid,
  from_squad_id uuid,
  to_squad_id uuid,
  reason text,
  transferred_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.leads (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid,
  assigned_to uuid,
  current_stage_id uuid,
  name text NOT NULL,
  email text,
  phone text,
  company text,
  "position" text,
  source text,
  temperature lead_temperature DEFAULT 'warm'::lead_temperature,
  cadence_day integer DEFAULT 1,
  last_contact_at timestamp with time zone,
  next_action text,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  lead_origin text,
  lead_channel text,
  referrer_url text,
  landing_page text,
  squad_id uuid,
  previous_assigned_to uuid,
  transferred_at timestamp with time zone,
  transferred_by uuid,
  transfer_reason text,
  expected_close_date date,
  deal_value numeric DEFAULT 0,
  bant_budget text,
  bant_authority text,
  bant_need text,
  bant_timing text,
  sdr_id uuid,
  closer_id uuid,
  sector_id uuid,
  phone_normalized text DEFAULT normalize_phone_br(phone),
  PRIMARY KEY (id)
);
CREATE TABLE public.mass_email_campaigns (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  template_id uuid,
  subject text NOT NULL,
  html_content text NOT NULL,
  target_type text DEFAULT 'all'::text NOT NULL,
  target_filters jsonb DEFAULT '{}'::jsonb,
  scheduled_at timestamp with time zone,
  sent_at timestamp with time zone,
  status text DEFAULT 'draft'::text,
  stats jsonb DEFAULT '{"sent": 0, "total": 0, "failed": 0}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.mass_email_recipients (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  campaign_id uuid NOT NULL,
  user_id uuid,
  email text NOT NULL,
  status text DEFAULT 'pending'::text,
  sent_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.materials (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid,
  organization_id uuid,
  name text NOT NULL,
  type text NOT NULL,
  url text NOT NULL,
  tags text[] DEFAULT '{}'::text[],
  objective text,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.message_reactions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  message_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  emoji text NOT NULL,
  user_id uuid,
  visitor_id text,
  reactor_type text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.notification_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  notification_type text NOT NULL,
  reference_id uuid,
  reference_date date DEFAULT CURRENT_DATE,
  sent_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  type notification_type DEFAULT 'system'::notification_type NOT NULL,
  title text NOT NULL,
  message text,
  action_url text,
  is_read boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  product_id uuid,
  admin_notification_id uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.objections (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid,
  organization_id uuid,
  category text NOT NULL,
  what_they_say text NOT NULL,
  what_they_mean text,
  suggested_response text NOT NULL,
  follow_up_question text,
  proof_material_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.orchestration_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  conversation_id uuid,
  lead_id uuid,
  channel text,
  message_in text,
  produto_id uuid,
  produto_nome text,
  intencao text,
  confianca numeric,
  contexto_extraido text,
  agent_routed_to uuid,
  action text NOT NULL,
  raw_response jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.org_ai_credentials (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  provider text NOT NULL,
  api_key_encrypted text NOT NULL,
  api_key_masked text,
  model_default text,
  last_verified_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.org_ai_routing (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  capability text NOT NULL,
  provider text NOT NULL,
  model text,
  fallback_to_lovable boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.organization_orchestrator_config (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  is_enabled boolean DEFAULT false NOT NULL,
  orchestrator_agent_id uuid,
  max_triage_questions integer DEFAULT 2 NOT NULL,
  min_confidence numeric DEFAULT 0.6 NOT NULL,
  fallback_to_human_after integer DEFAULT 2 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.organizations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  logo_url text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  email text,
  cnpj text,
  phone text,
  address jsonb,
  owner_id uuid,
  status text DEFAULT 'active'::text,
  max_users integer DEFAULT 10,
  max_products integer DEFAULT 5,
  features jsonb DEFAULT '{}'::jsonb,
  refund_policy text,
  payment_policy text,
  plan_id uuid,
  max_connections integer,
  cakto_subscription_id text,
  cakto_customer_email text,
  ai_debounce_ms integer DEFAULT 5000 NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.payment_links (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  created_by uuid,
  conversation_id uuid,
  lead_id uuid,
  title text NOT NULL,
  description text,
  amount numeric(12,2) NOT NULL,
  currency text DEFAULT 'BRL'::text NOT NULL,
  url text NOT NULL,
  status text DEFAULT 'sent'::text NOT NULL,
  opened_at timestamp with time zone,
  paid_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.pipeline_stages (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid NOT NULL,
  name text NOT NULL,
  color text DEFAULT '#6B7280'::text,
  order_index integer DEFAULT 0 NOT NULL,
  is_won boolean DEFAULT false,
  is_lost boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  description text,
  PRIMARY KEY (id)
);
CREATE TABLE public.platform_audit_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  actor_id uuid,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.platform_email_settings (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  provider text DEFAULT 'lovable_emails'::text,
  api_key_encrypted text,
  sender_email text DEFAULT 'noreply@bizonsales.com'::text,
  sender_name text DEFAULT 'Bizon Sales'::text,
  smtp_host text,
  smtp_port integer,
  smtp_user text,
  smtp_pass_encrypted text,
  reminder_days_before integer DEFAULT 3,
  reminder_on_due_date boolean DEFAULT true,
  alert_days_after integer DEFAULT 3,
  suspend_days_after integer DEFAULT 15,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.platform_email_templates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  description text,
  category text NOT NULL,
  subject text NOT NULL,
  html_content text NOT NULL,
  variables jsonb DEFAULT '[]'::jsonb NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  is_system boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.platform_plans (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  is_public boolean DEFAULT true NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  is_default boolean DEFAULT false NOT NULL,
  display_order integer DEFAULT 0 NOT NULL,
  price_monthly numeric(10,2) DEFAULT 0 NOT NULL,
  price_yearly numeric(10,2) DEFAULT 0 NOT NULL,
  trial_days integer DEFAULT 7 NOT NULL,
  grace_period_days integer DEFAULT 3 NOT NULL,
  max_users integer DEFAULT 5 NOT NULL,
  max_connections integer DEFAULT 1 NOT NULL,
  max_sectors integer DEFAULT 3 NOT NULL,
  max_products integer DEFAULT 5 NOT NULL,
  max_contacts integer DEFAULT 1000 NOT NULL,
  max_messages_month integer DEFAULT 5000 NOT NULL,
  max_ai_tokens_month integer DEFAULT 100000 NOT NULL,
  feature_whatsapp boolean DEFAULT true NOT NULL,
  feature_facebook boolean DEFAULT false NOT NULL,
  feature_instagram boolean DEFAULT false NOT NULL,
  feature_campaigns boolean DEFAULT false NOT NULL,
  feature_scheduling boolean DEFAULT true NOT NULL,
  feature_internal_chat boolean DEFAULT true NOT NULL,
  feature_external_api boolean DEFAULT false NOT NULL,
  feature_kanban boolean DEFAULT true NOT NULL,
  feature_pipeline boolean DEFAULT true NOT NULL,
  feature_integrations boolean DEFAULT false NOT NULL,
  feature_audio_transcription_ai boolean DEFAULT false NOT NULL,
  feature_text_correction_ai boolean DEFAULT false NOT NULL,
  feature_ai_agents boolean DEFAULT false NOT NULL,
  feature_voice_agents boolean DEFAULT false NOT NULL,
  feature_outreach boolean DEFAULT false NOT NULL,
  feature_capture_funnels boolean DEFAULT false NOT NULL,
  feature_forms boolean DEFAULT true NOT NULL,
  feature_webhooks boolean DEFAULT false NOT NULL,
  extra_features jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  checkout_url text,
  highlight_label text,
  cakto_product_id text,
  checkout_url_cakto text,
  PRIMARY KEY (id)
);
CREATE TABLE public.platform_release_reads (
  user_id uuid NOT NULL,
  release_id uuid NOT NULL,
  read_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (user_id, release_id)
);
CREATE TABLE public.platform_releases (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  version text,
  title text NOT NULL,
  summary text,
  release_types text[] DEFAULT '{}'::text[] NOT NULL,
  content_json jsonb,
  content_html text,
  cover_image_url text,
  is_published boolean DEFAULT false NOT NULL,
  published_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.platform_settings (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  logo_url text,
  logo_dark_url text,
  favicon_url text,
  platform_name text DEFAULT 'Bizon Sales'::text,
  support_email text,
  primary_color text DEFAULT '#10b981'::text,
  footer_text text DEFAULT '© 2026 Bizon Sales. Todos os direitos reservados.'::text,
  terms_url text,
  privacy_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  login_headline text,
  login_subheadline text,
  login_stats_enabled boolean DEFAULT true,
  powered_by_text text DEFAULT 'Powered by'::text,
  evolution_go_url text,
  evolution_go_global_api_key text,
  accent_color text DEFAULT '#84CC16'::text,
  gradient_style text DEFAULT 'vendus'::text,
  gradient_custom jsonb,
  border_radius integer DEFAULT 12,
  default_theme text DEFAULT 'dark'::text,
  font_family text DEFAULT 'Inter'::text,
  font_url text,
  base_font_size integer DEFAULT 16,
  login_bg_image_url text,
  login_logo_position text DEFAULT 'left'::text,
  hide_widget_branding boolean DEFAULT false,
  widget_accent_color text,
  browser_title text,
  meta_description text,
  og_image_url text,
  twitter_handle text,
  default_language text DEFAULT 'pt-BR'::text,
  login_bg_layout text DEFAULT 'split-left'::text NOT NULL,
  default_password_changed boolean DEFAULT false NOT NULL,
  google_oauth_configured boolean DEFAULT false NOT NULL,
  remix_setup_completed boolean DEFAULT false NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.post_sale_event_actions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  event_type text NOT NULL,
  target_stage_id uuid,
  email_template_id uuid,
  agent_id uuid,
  agent_objective text,
  agent_extra_context text,
  notify_user_id uuid,
  is_active boolean DEFAULT true NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  add_tag_ids uuid[] DEFAULT '{}'::uuid[] NOT NULL,
  remove_tag_ids uuid[] DEFAULT '{}'::uuid[] NOT NULL,
  send_mode text DEFAULT 'none'::text NOT NULL,
  flow_id uuid,
  inline_message text,
  message_channel text DEFAULT 'whatsapp'::text NOT NULL,
  deal_outcome text DEFAULT 'none'::text NOT NULL,
  deal_value_source text DEFAULT 'none'::text NOT NULL,
  deal_value_manual numeric,
  assign_sector_id uuid,
  assign_user_id uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.post_sale_event_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid,
  event_type text NOT NULL,
  lead_id uuid,
  source text NOT NULL,
  action_id uuid,
  executed_actions jsonb DEFAULT '[]'::jsonb NOT NULL,
  event_data jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.product_agents (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid,
  name character varying(100) NOT NULL,
  description text,
  avatar_url text,
  agent_type character varying(50) DEFAULT 'custom'::character varying NOT NULL,
  primary_objective text NOT NULL,
  can_do text[] DEFAULT '{}'::text[],
  cannot_do text[] DEFAULT '{}'::text[],
  handoff_triggers text[] DEFAULT '{}'::text[],
  end_conversation_triggers text[] DEFAULT '{}'::text[],
  tone_style character varying(30) DEFAULT 'friendly'::character varying,
  message_style character varying(20) DEFAULT 'balanced'::character varying,
  always_end_with_question boolean DEFAULT true,
  additional_prompt text,
  required_phrases text[] DEFAULT '{}'::text[],
  prohibited_phrases text[] DEFAULT '{}'::text[],
  auto_tag_leads boolean DEFAULT true,
  default_tags text[] DEFAULT '{}'::text[],
  can_update_pipeline boolean DEFAULT true,
  can_create_tasks boolean DEFAULT true,
  can_schedule_meetings boolean DEFAULT true,
  active_in_funnels boolean DEFAULT true,
  active_in_chat boolean DEFAULT true,
  active_in_widget boolean DEFAULT true,
  active_in_inbox boolean DEFAULT true,
  active_in_copilot boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  can_apply_tags boolean DEFAULT false NOT NULL,
  can_update_lead boolean DEFAULT false NOT NULL,
  can_send_emails boolean DEFAULT false NOT NULL,
  can_send_materials boolean DEFAULT false NOT NULL,
  can_trigger_flows boolean DEFAULT false NOT NULL,
  can_transfer boolean DEFAULT false NOT NULL,
  can_notify boolean DEFAULT false NOT NULL,
  can_add_notes boolean DEFAULT false NOT NULL,
  can_start_cadence boolean DEFAULT false NOT NULL,
  can_qualify boolean DEFAULT false NOT NULL,
  tool_configs jsonb DEFAULT '{}'::jsonb NOT NULL,
  active_in_whatsapp boolean DEFAULT true,
  active_in_instagram boolean DEFAULT true,
  active_in_facebook boolean DEFAULT true,
  activation_keywords text[] DEFAULT '{}'::text[] NOT NULL,
  activation_phrases text[] DEFAULT '{}'::text[] NOT NULL,
  activation_priority integer DEFAULT 0 NOT NULL,
  activation_scope text DEFAULT 'all'::text NOT NULL,
  takeover_on_match boolean DEFAULT true NOT NULL,
  evolution_instance_id uuid,
  handoff_outgoing_message text,
  handoff_incoming_message text,
  handoff_delay_seconds integer DEFAULT 4 NOT NULL,
  message_delay_seconds integer DEFAULT 2 NOT NULL,
  handoff_include_summary boolean DEFAULT true NOT NULL,
  welcome_enabled boolean DEFAULT false NOT NULL,
  welcome_message text,
  quick_menu_mode text DEFAULT 'off'::text NOT NULL,
  quick_menu_intro text,
  quick_menu_options jsonb DEFAULT '[]'::jsonb NOT NULL,
  quick_menu_invalid_message text,
  enable_audio_transcription boolean DEFAULT true NOT NULL,
  enable_image_vision boolean DEFAULT true NOT NULL,
  default_schedule_user_id uuid,
  allowed_event_type_ids uuid[] DEFAULT '{}'::uuid[],
  booking_notification_user_ids uuid[] DEFAULT '{}'::uuid[],
  booking_notify_org_admins boolean DEFAULT false,
  PRIMARY KEY (id)
);
CREATE TABLE public.product_catalog_items (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid,
  external_id text,
  title text NOT NULL,
  description text,
  price numeric(12,2),
  currency text DEFAULT 'BRL'::text,
  url text,
  thumbnail_url text,
  images text[] DEFAULT '{}'::text[],
  attributes jsonb DEFAULT '{}'::jsonb,
  tags text[] DEFAULT '{}'::text[],
  source_type text DEFAULT 'manual'::text NOT NULL,
  source_url text,
  is_active boolean DEFAULT true NOT NULL,
  search_vector tsvector,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  videos text[] DEFAULT '{}'::text[] NOT NULL,
  documents jsonb DEFAULT '[]'::jsonb NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.product_ctas (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid,
  organization_id uuid NOT NULL,
  cta_type text NOT NULL,
  label text NOT NULL,
  action_url text,
  whatsapp_number text,
  whatsapp_message text,
  icon text DEFAULT 'link'::text,
  trigger_keywords text[],
  intent_level text DEFAULT 'medium'::text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  video_url text,
  PRIMARY KEY (id)
);
CREATE TABLE public.product_knowledge_sources (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  source_type character varying NOT NULL,
  title character varying NOT NULL,
  description text,
  extracted_content text,
  raw_content text,
  file_url text,
  file_type character varying,
  file_size integer,
  source_url text,
  last_crawled_at timestamp with time zone,
  video_id character varying,
  video_duration integer,
  transcript text,
  question text,
  answer text,
  data_category character varying,
  data_json jsonb,
  processing_status character varying DEFAULT 'pending'::character varying,
  processing_error text,
  processed_at timestamp with time zone,
  is_active boolean DEFAULT true,
  is_synced boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.product_offers (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid,
  name text NOT NULL,
  role text DEFAULT 'main'::text NOT NULL,
  cakto_product_id text,
  external_source text DEFAULT 'cakto'::text,
  price numeric(12,2),
  currency text DEFAULT 'BRL'::text,
  "position" integer DEFAULT 0,
  is_active boolean DEFAULT true NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.product_onboarding_state (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid,
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  current_step integer DEFAULT 1,
  total_steps integer DEFAULT 8,
  draft_data jsonb DEFAULT '{}'::jsonb,
  ai_optimizations jsonb DEFAULT '[]'::jsonb,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.product_suites (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  slug text,
  description text,
  icon_url text,
  color text DEFAULT '#10B981'::text,
  status text DEFAULT 'active'::text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.product_training_videos (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  product_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  video_url text NOT NULL,
  thumbnail_url text,
  duration_seconds integer,
  order_index integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.products (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  pitch_15s text,
  pitch_30s text,
  pitch_2min text,
  icp text,
  differentials text[] DEFAULT '{}'::text[],
  pricing jsonb DEFAULT '[]'::jsonb,
  status product_status DEFAULT 'draft'::product_status,
  settings jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  logo_url text,
  banner_url text,
  product_image_url text,
  category text,
  short_description text,
  external_links jsonb DEFAULT '{}'::jsonb,
  benefits text,
  objections text,
  plans text,
  payment_conditions text,
  guarantee text,
  bonuses text,
  discount_policy text,
  knowledge_base text,
  suite_id uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  organization_id uuid,
  full_name text NOT NULL,
  email text NOT NULL,
  avatar_url text,
  phone text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  booking_slug text,
  booking_bio text,
  recovery_whatsapp text,
  work_start_time time without time zone DEFAULT '00:00:00'::time without time zone,
  work_end_time time without time zone DEFAULT '23:59:00'::time without time zone,
  farewell_message text,
  default_theme text DEFAULT 'system'::text,
  default_menu_state text DEFAULT 'open'::text,
  default_connection_id uuid,
  guided_onboarding_completed_at timestamp with time zone,
  guided_onboarding_skipped_at timestamp with time zone,
  PRIMARY KEY (id)
);
CREATE TABLE public.quick_replies (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  category text DEFAULT 'general'::text NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  shortcut text,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.sales_goals (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  product_id uuid,
  organization_id uuid,
  period_start date NOT NULL,
  period_end date NOT NULL,
  target_value numeric DEFAULT 0 NOT NULL,
  target_deals integer DEFAULT 0 NOT NULL,
  achieved_value numeric DEFAULT 0,
  achieved_deals integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  created_by uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.sales_leads (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  company_name text NOT NULL,
  contact_name text NOT NULL,
  email text NOT NULL,
  phone text,
  company_size text,
  segment text,
  current_tools text,
  main_challenge text,
  message text,
  status text DEFAULT 'new'::text,
  notes text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.sales_squads (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  description text,
  icon_url text,
  product_id uuid,
  organization_id uuid NOT NULL,
  leader_id uuid,
  color text DEFAULT '#6366F1'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.sankhya_mappings (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  entity_type text NOT NULL,
  local_id uuid NOT NULL,
  sankhya_id text NOT NULL,
  last_sync_at timestamp with time zone,
  sync_status text DEFAULT 'pending'::text,
  sync_direction text DEFAULT 'from_sankhya'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.sankhya_sync_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  sync_type text NOT NULL,
  entity_type text NOT NULL,
  records_processed integer DEFAULT 0,
  records_success integer DEFAULT 0,
  records_failed integer DEFAULT 0,
  error_details jsonb,
  started_at timestamp with time zone DEFAULT now(),
  finished_at timestamp with time zone,
  status text DEFAULT 'running'::text,
  PRIMARY KEY (id)
);
CREATE TABLE public.scheduled_messages (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  conversation_id uuid,
  content text NOT NULL,
  scheduled_at timestamp with time zone NOT NULL,
  status text DEFAULT 'pending'::text,
  created_by uuid,
  organization_id uuid,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.sector_members (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  sector_id uuid NOT NULL,
  user_id uuid NOT NULL,
  joined_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.sectors (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  color text DEFAULT '#3B82F6'::text,
  description text,
  bot_order integer DEFAULT 0,
  greeting_message text,
  farewell_message text,
  auto_close_ticket boolean DEFAULT false,
  enable_scheduling boolean DEFAULT false,
  rotation_enabled boolean DEFAULT false,
  rotation_strategy sector_rotation_strategy DEFAULT 'round_robin'::sector_rotation_strategy,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  icon text DEFAULT 'Building2'::text,
  is_default boolean DEFAULT false NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.squad_members (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  squad_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text DEFAULT 'member'::text,
  joined_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.stage_values (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  stage_id uuid NOT NULL,
  product_id uuid NOT NULL,
  expected_value numeric DEFAULT 0,
  probability_percent numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid,
  plan_type text DEFAULT 'trial'::text,
  status text DEFAULT 'active'::text,
  price_monthly numeric(10,2) DEFAULT 0,
  billing_cycle text DEFAULT 'monthly'::text,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  trial_ends_at timestamp with time zone,
  canceled_at timestamp with time zone,
  payment_method jsonb,
  stripe_customer_id text,
  stripe_subscription_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  plan_id uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.support_messages (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  ticket_id uuid NOT NULL,
  author_id uuid NOT NULL,
  author_role text NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.support_tickets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  created_by uuid NOT NULL,
  subject text NOT NULL,
  category text,
  status support_ticket_status DEFAULT 'open'::support_ticket_status NOT NULL,
  priority support_ticket_priority DEFAULT 'normal'::support_ticket_priority NOT NULL,
  assigned_super_admin uuid,
  last_message_at timestamp with time zone DEFAULT now() NOT NULL,
  last_message_by_role text DEFAULT 'admin'::text NOT NULL,
  unread_for_admin boolean DEFAULT false NOT NULL,
  unread_for_super_admin boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.suppressed_emails (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email text NOT NULL,
  reason text NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.tag_automations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid,
  event_type text NOT NULL,
  tag_id_to_add uuid NOT NULL,
  tag_id_to_remove uuid,
  is_active boolean DEFAULT true NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.tasks (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  lead_id uuid,
  product_id uuid,
  title text NOT NULL,
  description text,
  type text DEFAULT 'follow_up'::text,
  status task_status DEFAULT 'pending'::task_status,
  priority task_priority DEFAULT 'medium'::task_priority,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  created_by uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.team_invitations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email text NOT NULL,
  role app_role DEFAULT 'seller'::app_role NOT NULL,
  squad_id uuid,
  invited_by uuid,
  organization_id uuid NOT NULL,
  token text DEFAULT encode(extensions.gen_random_bytes(32), 'hex'::text) NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval) NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.user_availability (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  day_of_week integer NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_available boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.user_badges (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  badge_type text NOT NULL,
  badge_name text NOT NULL,
  description text,
  earned_at timestamp with time zone DEFAULT now() NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  PRIMARY KEY (id)
);
CREATE TABLE public.user_notification_settings (
  user_id uuid NOT NULL,
  organization_id uuid,
  notify_new_tickets boolean DEFAULT true,
  notify_status_change boolean DEFAULT true,
  notify_new_messages boolean DEFAULT true,
  notify_groups boolean DEFAULT false,
  notify_unassigned_sector_tickets boolean DEFAULT false,
  notify_appointments boolean DEFAULT true,
  push_enabled boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (user_id)
);
CREATE TABLE public.user_permissions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  view_queue_conversations boolean DEFAULT false,
  view_other_users_conversations boolean DEFAULT false,
  view_other_queues_conversations boolean DEFAULT false,
  allow_close_pending_tickets boolean DEFAULT true,
  view_all_contacts boolean DEFAULT false,
  allow_pipeline boolean DEFAULT false,
  allow_manage_client_portfolio boolean DEFAULT false,
  view_all_kanban_cards boolean DEFAULT false,
  view_all_schedules boolean DEFAULT false,
  allow_dashboard boolean DEFAULT false,
  allow_inbox_panel boolean DEFAULT false,
  allow_groups boolean DEFAULT false,
  allow_connection_actions boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  view_unassigned_sector_tickets boolean DEFAULT false,
  view_schedules_mode text DEFAULT 'mine_only'::text,
  PRIMARY KEY (id)
);
CREATE TABLE public.user_product_assignments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  assigned_by uuid,
  monthly_goal numeric(10,2) DEFAULT 0,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.user_roles (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  role app_role DEFAULT 'seller'::app_role NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.user_status (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  status text DEFAULT 'offline'::text NOT NULL,
  last_status_change timestamp with time zone DEFAULT now() NOT NULL,
  active_leads_count integer DEFAULT 0 NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.webchat_agent_configs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  widget_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid,
  agent_name text DEFAULT 'Assistente Virtual'::text,
  agent_avatar_url text,
  system_prompt text DEFAULT 'Você é um assistente virtual prestativo e amigável. Responda de forma clara e objetiva.'::text,
  knowledge_base text,
  faq jsonb DEFAULT '[]'::jsonb,
  handoff_triggers text[] DEFAULT ARRAY['falar com atendente'::text, 'falar com humano'::text, 'atendente'::text, 'quero comprar'::text, 'preço'::text, 'valor'::text],
  auto_handoff_enabled boolean DEFAULT true,
  greeting_message text DEFAULT 'Olá! Sou o assistente virtual. Como posso ajudar você hoje?'::text,
  fallback_message text DEFAULT 'Desculpe, não entendi. Posso transferir você para um atendente?'::text,
  handoff_message text DEFAULT 'Certo! Estou transferindo você para um atendente. Aguarde um momento.'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  temperature numeric DEFAULT 0.7,
  max_tokens integer DEFAULT 500,
  persona_style text DEFAULT 'friendly'::text,
  use_product_brain boolean DEFAULT true,
  collect_before_chat boolean DEFAULT true,
  required_fields text[] DEFAULT ARRAY['name'::text, 'whatsapp'::text],
  welcome_flow jsonb DEFAULT '[]'::jsonb,
  sales_prompt text,
  sales_context text,
  chunked_messages_enabled boolean DEFAULT true,
  typing_delay_ms integer DEFAULT 1500,
  max_message_length integer DEFAULT 150,
  PRIMARY KEY (id)
);
CREATE TABLE public.webchat_assignment_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  conversation_id uuid NOT NULL,
  from_user_id uuid,
  to_user_id uuid,
  action text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.webchat_conversations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  widget_id uuid,
  channel text DEFAULT 'web_chat'::text NOT NULL,
  status webchat_conversation_status DEFAULT 'bot_active'::webchat_conversation_status NOT NULL,
  visitor_id text NOT NULL,
  visitor_name text,
  visitor_email text,
  visitor_phone text,
  visitor_ip text,
  visitor_user_agent text,
  assigned_user_id uuid,
  lead_id uuid,
  current_page_url text,
  referrer_url text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  last_message_at timestamp with time zone,
  unread_count_agents integer DEFAULT 0,
  first_response_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  closed_at timestamp with time zone,
  visitor_whatsapp text,
  lead_created_at timestamp with time zone,
  data_collected boolean DEFAULT false,
  collected_data jsonb DEFAULT '{}'::jsonb,
  current_flow_id uuid,
  current_block_id text,
  flow_variables jsonb DEFAULT '{}'::jsonb,
  flow_completed boolean DEFAULT false,
  current_agent_id uuid,
  evolution_instance_id uuid,
  orchestrator_state text DEFAULT 'triagem'::text NOT NULL,
  orchestrator_context text,
  orchestrator_question_count integer DEFAULT 0 NOT NULL,
  detected_intent text,
  flow_source text,
  sector_id uuid,
  meeting_scheduled_at timestamp with time zone,
  meeting_event_id text,
  meeting_metadata jsonb,
  visitor_avatar_url text,
  product_id uuid,
  accepted_at timestamp with time zone,
  accepted_by uuid,
  needs_human boolean DEFAULT false NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE public.webchat_messages (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  conversation_id uuid NOT NULL,
  direction text NOT NULL,
  sender_type text NOT NULL,
  sender_id uuid,
  content text NOT NULL,
  content_type text DEFAULT 'text'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  message_type text DEFAULT 'text'::text,
  buttons jsonb,
  video_url text,
  is_deleted boolean DEFAULT false,
  edited_at timestamp with time zone,
  original_content text,
  reply_to_message_id uuid,
  is_starred boolean DEFAULT false,
  forwarded_from_message_id uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.webchat_widgets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text DEFAULT 'Widget Principal'::text NOT NULL,
  is_active boolean DEFAULT true,
  primary_color text DEFAULT '#14B8A6'::text,
  secondary_color text DEFAULT '#0F172A'::text,
  welcome_message text DEFAULT 'Olá! Como posso ajudar?'::text,
  placeholder_text text DEFAULT 'Digite sua mensagem...'::text,
  "position" text DEFAULT 'bottom-right'::text,
  avatar_url text,
  auto_open_delay integer,
  business_hours jsonb DEFAULT '{"enabled": false}'::jsonb,
  offline_message text DEFAULT 'Estamos offline no momento. Deixe sua mensagem!'::text,
  collect_email boolean DEFAULT false,
  collect_phone boolean DEFAULT false,
  collect_name boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  product_id uuid,
  PRIMARY KEY (id)
);
CREATE TABLE public.webhook_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  webhook_id uuid NOT NULL,
  request_method text NOT NULL,
  request_headers jsonb,
  request_body jsonb,
  request_ip text,
  parsed_fields jsonb,
  status text DEFAULT 'pending'::text,
  actions_executed jsonb DEFAULT '[]'::jsonb,
  error_message text,
  lead_id uuid,
  processing_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.webhook_sample_requests (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  webhook_id uuid NOT NULL,
  name text,
  request_body jsonb NOT NULL,
  extracted_fields jsonb NOT NULL,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE TABLE public.webhooks (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  is_active boolean DEFAULT false,
  is_test_mode boolean DEFAULT true,
  secret_key text,
  allowed_ips text[],
  product_id uuid,
  actions jsonb DEFAULT '[]'::jsonb,
  identification_config jsonb DEFAULT '{}'::jsonb,
  requests_count integer DEFAULT 0,
  requests_this_month integer DEFAULT 0,
  last_request_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  squad_id uuid,
  PRIMARY KEY (id)
);
