-- ============================================================
-- 03_constraints_and_indexes.sql
-- ============================================================

-- FOREIGN KEYS
ALTER TABLE public.admin_agent_messages ADD CONSTRAINT admin_agent_messages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.admin_notifications ADD CONSTRAINT admin_notifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.admin_notifications ADD CONSTRAINT admin_notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.agent_action_logs ADD CONSTRAINT agent_action_logs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES product_agents(id) ON DELETE SET NULL;
ALTER TABLE public.agent_action_logs ADD CONSTRAINT agent_action_logs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE SET NULL;
ALTER TABLE public.agent_action_logs ADD CONSTRAINT agent_action_logs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.agent_action_logs ADD CONSTRAINT agent_action_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.agent_action_logs ADD CONSTRAINT agent_action_logs_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.agent_activation_logs ADD CONSTRAINT agent_activation_logs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE SET NULL;
ALTER TABLE public.agent_activation_logs ADD CONSTRAINT agent_activation_logs_from_agent_id_fkey FOREIGN KEY (from_agent_id) REFERENCES product_agents(id) ON DELETE SET NULL;
ALTER TABLE public.agent_activation_logs ADD CONSTRAINT agent_activation_logs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.agent_activation_logs ADD CONSTRAINT agent_activation_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.agent_activation_logs ADD CONSTRAINT agent_activation_logs_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.agent_activation_logs ADD CONSTRAINT agent_activation_logs_to_agent_id_fkey FOREIGN KEY (to_agent_id) REFERENCES product_agents(id) ON DELETE SET NULL;
ALTER TABLE public.agent_post_sale_scenarios ADD CONSTRAINT agent_post_sale_scenarios_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.agent_post_sale_scenarios ADD CONSTRAINT agent_post_sale_scenarios_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.agent_routing_rules ADD CONSTRAINT agent_routing_rules_target_specialist_id_fkey FOREIGN KEY (target_specialist_id) REFERENCES agent_specialists(id) ON DELETE CASCADE;
ALTER TABLE public.agent_training_materials ADD CONSTRAINT agent_training_materials_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES product_agents(id) ON DELETE CASCADE;
ALTER TABLE public.agent_training_materials ADD CONSTRAINT agent_training_materials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.agent_training_materials ADD CONSTRAINT agent_training_materials_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.ai_audits ADD CONSTRAINT ai_audits_interaction_id_fkey FOREIGN KEY (interaction_id) REFERENCES interactions(id) ON DELETE CASCADE;
ALTER TABLE public.ai_insights ADD CONSTRAINT ai_insights_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.ai_insights ADD CONSTRAINT ai_insights_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.ai_insights ADD CONSTRAINT ai_insights_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.ai_knowledge_base ADD CONSTRAINT ai_knowledge_base_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.ai_knowledge_base ADD CONSTRAINT ai_knowledge_base_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.ai_outreach_queue ADD CONSTRAINT ai_outreach_queue_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES product_agents(id) ON DELETE SET NULL;
ALTER TABLE public.ai_outreach_queue ADD CONSTRAINT ai_outreach_queue_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE SET NULL;
ALTER TABLE public.ai_outreach_queue ADD CONSTRAINT ai_outreach_queue_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.ai_outreach_queue ADD CONSTRAINT ai_outreach_queue_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.ai_outreach_queue ADD CONSTRAINT ai_outreach_queue_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.ai_outreach_queue ADD CONSTRAINT ai_outreach_queue_webhook_id_fkey FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE SET NULL;
ALTER TABLE public.ai_prompt_variants ADD CONSTRAINT ai_prompt_variants_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES ai_prompt_experiments(id) ON DELETE CASCADE;
ALTER TABLE public.ai_response_feedback ADD CONSTRAINT ai_response_feedback_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.ai_response_feedback ADD CONSTRAINT ai_response_feedback_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.ai_response_feedback ADD CONSTRAINT ai_response_feedback_message_id_fkey FOREIGN KEY (message_id) REFERENCES webchat_messages(id) ON DELETE CASCADE;
ALTER TABLE public.ai_response_feedback ADD CONSTRAINT ai_response_feedback_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE public.auto_notification_settings ADD CONSTRAINT auto_notification_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.availability_overrides ADD CONSTRAINT availability_overrides_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.availability_overrides ADD CONSTRAINT availability_overrides_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.billing_history ADD CONSTRAINT billing_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL;
ALTER TABLE public.billing_history ADD CONSTRAINT billing_history_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL;
ALTER TABLE public.booking_event_types ADD CONSTRAINT booking_event_types_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.booking_event_types ADD CONSTRAINT booking_event_types_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.booking_requests ADD CONSTRAINT booking_requests_calendar_event_id_fkey FOREIGN KEY (calendar_event_id) REFERENCES calendar_events(id) ON DELETE SET NULL;
ALTER TABLE public.booking_requests ADD CONSTRAINT booking_requests_event_type_id_fkey FOREIGN KEY (event_type_id) REFERENCES booking_event_types(id) ON DELETE CASCADE;
ALTER TABLE public.booking_requests ADD CONSTRAINT booking_requests_host_user_id_fkey FOREIGN KEY (host_user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.booking_requests ADD CONSTRAINT booking_requests_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.booking_requests ADD CONSTRAINT booking_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.business_holidays ADD CONSTRAINT business_holidays_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.business_hours ADD CONSTRAINT business_hours_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.cadence_templates ADD CONSTRAINT cadence_templates_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.cakto_credentials ADD CONSTRAINT cakto_credentials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.cakto_orders ADD CONSTRAINT cakto_orders_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.cakto_orders ADD CONSTRAINT cakto_orders_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.cakto_orders ADD CONSTRAINT cakto_orders_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES product_offers(id) ON DELETE SET NULL;
ALTER TABLE public.cakto_orders ADD CONSTRAINT cakto_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.cakto_orders ADD CONSTRAINT cakto_orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.cakto_recovery_config ADD CONSTRAINT cakto_recovery_config_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.cakto_recovery_config ADD CONSTRAINT cakto_recovery_config_recovery_agent_id_fkey FOREIGN KEY (recovery_agent_id) REFERENCES product_agents(id) ON DELETE SET NULL;
ALTER TABLE public.cakto_recovery_dispatches ADD CONSTRAINT cakto_recovery_dispatches_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES product_agents(id) ON DELETE SET NULL;
ALTER TABLE public.cakto_recovery_dispatches ADD CONSTRAINT cakto_recovery_dispatches_cakto_order_id_fkey FOREIGN KEY (cakto_order_id) REFERENCES cakto_orders(id) ON DELETE SET NULL;
ALTER TABLE public.cakto_recovery_dispatches ADD CONSTRAINT cakto_recovery_dispatches_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.cakto_recovery_dispatches ADD CONSTRAINT cakto_recovery_dispatches_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL;
ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_parent_event_id_fkey FOREIGN KEY (parent_event_id) REFERENCES calendar_events(id) ON DELETE CASCADE;
ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.capture_funnels ADD CONSTRAINT capture_funnels_assigned_squad_id_fkey FOREIGN KEY (assigned_squad_id) REFERENCES sales_squads(id) ON DELETE SET NULL;
ALTER TABLE public.capture_funnels ADD CONSTRAINT capture_funnels_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.capture_funnels ADD CONSTRAINT capture_funnels_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.capture_funnels ADD CONSTRAINT capture_funnels_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.capture_funnels ADD CONSTRAINT capture_funnels_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.catalog_sync_logs ADD CONSTRAINT catalog_sync_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.catalog_sync_logs ADD CONSTRAINT catalog_sync_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.catalog_sync_logs ADD CONSTRAINT catalog_sync_logs_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.chat_flows ADD CONSTRAINT chat_flows_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.chat_flows ADD CONSTRAINT chat_flows_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.chat_flows ADD CONSTRAINT chat_flows_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.commission_rules ADD CONSTRAINT commission_rules_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.commission_rules ADD CONSTRAINT commission_rules_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.commission_rules ADD CONSTRAINT commission_rules_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES pipeline_stages(id) ON DELETE SET NULL;
ALTER TABLE public.commission_rules ADD CONSTRAINT commission_rules_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.commissions ADD CONSTRAINT commissions_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE;
ALTER TABLE public.commissions ADD CONSTRAINT commissions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.commissions ADD CONSTRAINT commissions_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.commissions ADD CONSTRAINT commissions_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES commission_rules(id) ON DELETE SET NULL;
ALTER TABLE public.conversation_notes ADD CONSTRAINT conversation_notes_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_notes ADD CONSTRAINT conversation_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
ALTER TABLE public.conversation_transfers ADD CONSTRAINT conversation_transfers_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.conversation_transfers ADD CONSTRAINT conversation_transfers_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.conversation_transfers ADD CONSTRAINT conversation_transfers_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES profiles(id);
ALTER TABLE public.conversation_transfers ADD CONSTRAINT conversation_transfers_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES profiles(id);
ALTER TABLE public.custom_fields ADD CONSTRAINT custom_fields_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.deals ADD CONSTRAINT deals_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.deals ADD CONSTRAINT deals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.deals ADD CONSTRAINT deals_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.distribution_config ADD CONSTRAINT distribution_config_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.distribution_config ADD CONSTRAINT distribution_config_squad_id_fkey FOREIGN KEY (squad_id) REFERENCES sales_squads(id) ON DELETE CASCADE;
ALTER TABLE public.email_templates ADD CONSTRAINT email_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.evolution_instances ADD CONSTRAINT evolution_instances_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.facebook_lead_integrations ADD CONSTRAINT facebook_lead_integrations_assigned_squad_id_fkey FOREIGN KEY (assigned_squad_id) REFERENCES sales_squads(id);
ALTER TABLE public.facebook_lead_integrations ADD CONSTRAINT facebook_lead_integrations_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES profiles(id);
ALTER TABLE public.facebook_lead_integrations ADD CONSTRAINT facebook_lead_integrations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.facebook_lead_integrations ADD CONSTRAINT facebook_lead_integrations_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.facebook_lead_logs ADD CONSTRAINT facebook_lead_logs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES facebook_lead_integrations(id) ON DELETE CASCADE;
ALTER TABLE public.facebook_lead_logs ADD CONSTRAINT facebook_lead_logs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id);
ALTER TABLE public.form_blocks ADD CONSTRAINT form_blocks_form_id_fkey FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE;
ALTER TABLE public.form_submissions ADD CONSTRAINT form_submissions_form_id_fkey FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE;
ALTER TABLE public.form_submissions ADD CONSTRAINT form_submissions_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.form_templates ADD CONSTRAINT form_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.form_templates ADD CONSTRAINT form_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.forms ADD CONSTRAINT forms_assigned_squad_id_fkey FOREIGN KEY (assigned_squad_id) REFERENCES sales_squads(id);
ALTER TABLE public.forms ADD CONSTRAINT forms_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.forms ADD CONSTRAINT forms_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.forms ADD CONSTRAINT forms_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.funnel_analytics ADD CONSTRAINT funnel_analytics_funnel_id_fkey FOREIGN KEY (funnel_id) REFERENCES capture_funnels(id) ON DELETE CASCADE;
ALTER TABLE public.funnel_webhook_logs ADD CONSTRAINT funnel_webhook_logs_funnel_id_fkey FOREIGN KEY (funnel_id) REFERENCES capture_funnels(id) ON DELETE CASCADE;
ALTER TABLE public.funnel_webhook_logs ADD CONSTRAINT funnel_webhook_logs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.funnel_webhook_logs ADD CONSTRAINT funnel_webhook_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.google_calendar_connections ADD CONSTRAINT google_calendar_connections_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.help_article_feedback ADD CONSTRAINT help_article_feedback_article_id_fkey FOREIGN KEY (article_id) REFERENCES help_articles(id) ON DELETE CASCADE;
ALTER TABLE public.help_articles ADD CONSTRAINT help_articles_category_id_fkey FOREIGN KEY (category_id) REFERENCES help_categories(id) ON DELETE SET NULL;
ALTER TABLE public.help_articles ADD CONSTRAINT help_articles_related_release_id_fkey FOREIGN KEY (related_release_id) REFERENCES platform_releases(id) ON DELETE SET NULL;
ALTER TABLE public.hotmart_credentials ADD CONSTRAINT hotmart_credentials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.hotmart_orders ADD CONSTRAINT hotmart_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.hotmart_orders ADD CONSTRAINT hotmart_orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.hotmart_product_mapping ADD CONSTRAINT hotmart_product_mapping_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.hotmart_product_mapping ADD CONSTRAINT hotmart_product_mapping_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.integration_settings ADD CONSTRAINT integration_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.interactions ADD CONSTRAINT interactions_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.interactions ADD CONSTRAINT interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.lead_notes ADD CONSTRAINT lead_notes_author_id_fkey FOREIGN KEY (author_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.lead_notes ADD CONSTRAINT lead_notes_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.lead_queue ADD CONSTRAINT lead_queue_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.lead_queue ADD CONSTRAINT lead_queue_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.lead_queue ADD CONSTRAINT lead_queue_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.lead_queue ADD CONSTRAINT lead_queue_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.lead_queue ADD CONSTRAINT lead_queue_squad_id_fkey FOREIGN KEY (squad_id) REFERENCES sales_squads(id) ON DELETE SET NULL;
ALTER TABLE public.lead_semantic_memory ADD CONSTRAINT lead_semantic_memory_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.lead_stage_history ADD CONSTRAINT lead_stage_history_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.lead_stage_history ADD CONSTRAINT lead_stage_history_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES pipeline_stages(id) ON DELETE SET NULL;
ALTER TABLE public.lead_tag_assignments ADD CONSTRAINT lead_tag_assignments_applied_by_fkey FOREIGN KEY (applied_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.lead_tag_assignments ADD CONSTRAINT lead_tag_assignments_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.lead_tag_assignments ADD CONSTRAINT lead_tag_assignments_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES lead_tags(id) ON DELETE CASCADE;
ALTER TABLE public.lead_tags ADD CONSTRAINT lead_tags_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.lead_tags ADD CONSTRAINT lead_tags_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.lead_transfer_history ADD CONSTRAINT lead_transfer_history_from_squad_id_fkey FOREIGN KEY (from_squad_id) REFERENCES sales_squads(id);
ALTER TABLE public.lead_transfer_history ADD CONSTRAINT lead_transfer_history_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES profiles(id);
ALTER TABLE public.lead_transfer_history ADD CONSTRAINT lead_transfer_history_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.lead_transfer_history ADD CONSTRAINT lead_transfer_history_to_squad_id_fkey FOREIGN KEY (to_squad_id) REFERENCES sales_squads(id);
ALTER TABLE public.lead_transfer_history ADD CONSTRAINT lead_transfer_history_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES profiles(id);
ALTER TABLE public.lead_transfer_history ADD CONSTRAINT lead_transfer_history_transferred_by_fkey FOREIGN KEY (transferred_by) REFERENCES profiles(id);
ALTER TABLE public.leads ADD CONSTRAINT leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.leads ADD CONSTRAINT leads_closer_id_fkey FOREIGN KEY (closer_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.leads ADD CONSTRAINT leads_current_stage_id_fkey FOREIGN KEY (current_stage_id) REFERENCES pipeline_stages(id) ON DELETE SET NULL;
ALTER TABLE public.leads ADD CONSTRAINT leads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.leads ADD CONSTRAINT leads_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.leads ADD CONSTRAINT leads_sdr_id_fkey FOREIGN KEY (sdr_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.leads ADD CONSTRAINT leads_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE SET NULL;
ALTER TABLE public.leads ADD CONSTRAINT leads_squad_id_fkey FOREIGN KEY (squad_id) REFERENCES sales_squads(id) ON DELETE SET NULL;
ALTER TABLE public.mass_email_campaigns ADD CONSTRAINT mass_email_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.mass_email_campaigns ADD CONSTRAINT mass_email_campaigns_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.mass_email_campaigns ADD CONSTRAINT mass_email_campaigns_template_id_fkey FOREIGN KEY (template_id) REFERENCES email_templates(id) ON DELETE SET NULL;
ALTER TABLE public.mass_email_recipients ADD CONSTRAINT mass_email_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES mass_email_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.mass_email_recipients ADD CONSTRAINT mass_email_recipients_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.materials ADD CONSTRAINT materials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.materials ADD CONSTRAINT materials_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.message_reactions ADD CONSTRAINT message_reactions_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.message_reactions ADD CONSTRAINT message_reactions_message_id_fkey FOREIGN KEY (message_id) REFERENCES webchat_messages(id) ON DELETE CASCADE;
ALTER TABLE public.message_reactions ADD CONSTRAINT message_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.notification_logs ADD CONSTRAINT notification_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_admin_notification_id_fkey FOREIGN KEY (admin_notification_id) REFERENCES admin_notifications(id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.objections ADD CONSTRAINT objections_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.objections ADD CONSTRAINT objections_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.orchestration_logs ADD CONSTRAINT orchestration_logs_agent_routed_to_fkey FOREIGN KEY (agent_routed_to) REFERENCES product_agents(id) ON DELETE SET NULL;
ALTER TABLE public.orchestration_logs ADD CONSTRAINT orchestration_logs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE SET NULL;
ALTER TABLE public.orchestration_logs ADD CONSTRAINT orchestration_logs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.orchestration_logs ADD CONSTRAINT orchestration_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.orchestration_logs ADD CONSTRAINT orchestration_logs_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.organization_orchestrator_config ADD CONSTRAINT organization_orchestrator_config_orchestrator_agent_id_fkey FOREIGN KEY (orchestrator_agent_id) REFERENCES product_agents(id) ON DELETE SET NULL;
ALTER TABLE public.organization_orchestrator_config ADD CONSTRAINT organization_orchestrator_config_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.organizations ADD CONSTRAINT organizations_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id);
ALTER TABLE public.organizations ADD CONSTRAINT organizations_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES platform_plans(id) ON DELETE SET NULL;
ALTER TABLE public.payment_links ADD CONSTRAINT payment_links_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE SET NULL;
ALTER TABLE public.payment_links ADD CONSTRAINT payment_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.payment_links ADD CONSTRAINT payment_links_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.payment_links ADD CONSTRAINT payment_links_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.pipeline_stages ADD CONSTRAINT pipeline_stages_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.platform_audit_logs ADD CONSTRAINT platform_audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.platform_release_reads ADD CONSTRAINT platform_release_reads_release_id_fkey FOREIGN KEY (release_id) REFERENCES platform_releases(id) ON DELETE CASCADE;
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES product_agents(id) ON DELETE SET NULL;
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_assign_sector_id_fkey FOREIGN KEY (assign_sector_id) REFERENCES sectors(id) ON DELETE SET NULL;
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_assign_user_id_fkey FOREIGN KEY (assign_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_email_template_id_fkey FOREIGN KEY (email_template_id) REFERENCES email_templates(id) ON DELETE SET NULL;
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_flow_id_fkey FOREIGN KEY (flow_id) REFERENCES chat_flows(id) ON DELETE SET NULL;
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_notify_user_id_fkey FOREIGN KEY (notify_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_target_stage_id_fkey FOREIGN KEY (target_stage_id) REFERENCES pipeline_stages(id) ON DELETE SET NULL;
ALTER TABLE public.post_sale_event_logs ADD CONSTRAINT post_sale_event_logs_action_id_fkey FOREIGN KEY (action_id) REFERENCES post_sale_event_actions(id) ON DELETE SET NULL;
ALTER TABLE public.post_sale_event_logs ADD CONSTRAINT post_sale_event_logs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.post_sale_event_logs ADD CONSTRAINT post_sale_event_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.post_sale_event_logs ADD CONSTRAINT post_sale_event_logs_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.product_agents ADD CONSTRAINT product_agents_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.product_agents ADD CONSTRAINT product_agents_evolution_instance_id_fkey FOREIGN KEY (evolution_instance_id) REFERENCES evolution_instances(id) ON DELETE SET NULL;
ALTER TABLE public.product_agents ADD CONSTRAINT product_agents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.product_agents ADD CONSTRAINT product_agents_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_catalog_items ADD CONSTRAINT product_catalog_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.product_catalog_items ADD CONSTRAINT product_catalog_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.product_ctas ADD CONSTRAINT product_ctas_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.product_ctas ADD CONSTRAINT product_ctas_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_knowledge_sources ADD CONSTRAINT product_knowledge_sources_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE public.product_knowledge_sources ADD CONSTRAINT product_knowledge_sources_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_offers ADD CONSTRAINT product_offers_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.product_onboarding_state ADD CONSTRAINT product_onboarding_state_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE public.product_onboarding_state ADD CONSTRAINT product_onboarding_state_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_training_videos ADD CONSTRAINT product_training_videos_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.product_training_videos ADD CONSTRAINT product_training_videos_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.product_training_videos ADD CONSTRAINT product_training_videos_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.products ADD CONSTRAINT products_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_suite_id_fkey FOREIGN KEY (suite_id) REFERENCES product_suites(id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL;
ALTER TABLE public.quick_replies ADD CONSTRAINT quick_replies_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.quick_replies ADD CONSTRAINT quick_replies_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.sales_goals ADD CONSTRAINT sales_goals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.sales_goals ADD CONSTRAINT sales_goals_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.sales_squads ADD CONSTRAINT sales_squads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.sales_squads ADD CONSTRAINT sales_squads_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.sankhya_mappings ADD CONSTRAINT sankhya_mappings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE public.sankhya_sync_logs ADD CONSTRAINT sankhya_sync_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE public.scheduled_messages ADD CONSTRAINT scheduled_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.scheduled_messages ADD CONSTRAINT scheduled_messages_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.scheduled_messages ADD CONSTRAINT scheduled_messages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE public.sector_members ADD CONSTRAINT sector_members_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE CASCADE;
ALTER TABLE public.sector_members ADD CONSTRAINT sector_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.squad_members ADD CONSTRAINT squad_members_squad_id_fkey FOREIGN KEY (squad_id) REFERENCES sales_squads(id) ON DELETE CASCADE;
ALTER TABLE public.stage_values ADD CONSTRAINT stage_values_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.stage_values ADD CONSTRAINT stage_values_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES pipeline_stages(id) ON DELETE CASCADE;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES platform_plans(id) ON DELETE SET NULL;
ALTER TABLE public.support_messages ADD CONSTRAINT support_messages_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.support_messages ADD CONSTRAINT support_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
ALTER TABLE public.support_tickets ADD CONSTRAINT support_tickets_assigned_super_admin_fkey FOREIGN KEY (assigned_super_admin) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.support_tickets ADD CONSTRAINT support_tickets_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.support_tickets ADD CONSTRAINT support_tickets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.tag_automations ADD CONSTRAINT tag_automations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.tag_automations ADD CONSTRAINT tag_automations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.tag_automations ADD CONSTRAINT tag_automations_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.tag_automations ADD CONSTRAINT tag_automations_tag_id_to_add_fkey FOREIGN KEY (tag_id_to_add) REFERENCES lead_tags(id) ON DELETE CASCADE;
ALTER TABLE public.tag_automations ADD CONSTRAINT tag_automations_tag_id_to_remove_fkey FOREIGN KEY (tag_id_to_remove) REFERENCES lead_tags(id) ON DELETE SET NULL;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.team_invitations ADD CONSTRAINT team_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.team_invitations ADD CONSTRAINT team_invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.team_invitations ADD CONSTRAINT team_invitations_squad_id_fkey FOREIGN KEY (squad_id) REFERENCES sales_squads(id) ON DELETE SET NULL;
ALTER TABLE public.user_availability ADD CONSTRAINT user_availability_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.user_availability ADD CONSTRAINT user_availability_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.user_permissions ADD CONSTRAINT user_permissions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.user_permissions ADD CONSTRAINT user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_product_assignments ADD CONSTRAINT user_product_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id);
ALTER TABLE public.user_product_assignments ADD CONSTRAINT user_product_assignments_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.user_product_assignments ADD CONSTRAINT user_product_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_status ADD CONSTRAINT user_status_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.user_status ADD CONSTRAINT user_status_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.webchat_agent_configs ADD CONSTRAINT webchat_agent_configs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.webchat_agent_configs ADD CONSTRAINT webchat_agent_configs_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.webchat_agent_configs ADD CONSTRAINT webchat_agent_configs_widget_id_fkey FOREIGN KEY (widget_id) REFERENCES webchat_widgets(id) ON DELETE CASCADE;
ALTER TABLE public.webchat_assignment_events ADD CONSTRAINT webchat_assignment_events_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.webchat_assignment_events ADD CONSTRAINT webchat_assignment_events_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.webchat_assignment_events ADD CONSTRAINT webchat_assignment_events_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.webchat_conversations ADD CONSTRAINT webchat_conversations_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.webchat_conversations ADD CONSTRAINT webchat_conversations_current_agent_id_fkey FOREIGN KEY (current_agent_id) REFERENCES product_agents(id) ON DELETE SET NULL;
ALTER TABLE public.webchat_conversations ADD CONSTRAINT webchat_conversations_evolution_instance_id_fkey FOREIGN KEY (evolution_instance_id) REFERENCES evolution_instances(id) ON DELETE SET NULL;
ALTER TABLE public.webchat_conversations ADD CONSTRAINT webchat_conversations_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.webchat_conversations ADD CONSTRAINT webchat_conversations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.webchat_conversations ADD CONSTRAINT webchat_conversations_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.webchat_conversations ADD CONSTRAINT webchat_conversations_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE SET NULL;
ALTER TABLE public.webchat_conversations ADD CONSTRAINT webchat_conversations_widget_id_fkey FOREIGN KEY (widget_id) REFERENCES webchat_widgets(id) ON DELETE CASCADE;
ALTER TABLE public.webchat_messages ADD CONSTRAINT webchat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES webchat_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.webchat_messages ADD CONSTRAINT webchat_messages_forwarded_from_message_id_fkey FOREIGN KEY (forwarded_from_message_id) REFERENCES webchat_messages(id);
ALTER TABLE public.webchat_messages ADD CONSTRAINT webchat_messages_reply_to_message_id_fkey FOREIGN KEY (reply_to_message_id) REFERENCES webchat_messages(id);
ALTER TABLE public.webchat_messages ADD CONSTRAINT webchat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.webchat_widgets ADD CONSTRAINT webchat_widgets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.webchat_widgets ADD CONSTRAINT webchat_widgets_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.webhook_logs ADD CONSTRAINT webhook_logs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.webhook_logs ADD CONSTRAINT webhook_logs_webhook_id_fkey FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE;
ALTER TABLE public.webhook_sample_requests ADD CONSTRAINT webhook_sample_requests_webhook_id_fkey FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE;
ALTER TABLE public.webhooks ADD CONSTRAINT webhooks_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.webhooks ADD CONSTRAINT webhooks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE public.webhooks ADD CONSTRAINT webhooks_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.webhooks ADD CONSTRAINT webhooks_squad_id_fkey FOREIGN KEY (squad_id) REFERENCES sales_squads(id) ON DELETE SET NULL;

-- UNIQUE CONSTRAINTS
ALTER TABLE public.auto_notification_settings ADD CONSTRAINT auto_notification_settings_organization_id_key UNIQUE (organization_id);
ALTER TABLE public.availability_overrides ADD CONSTRAINT availability_overrides_user_id_date_key UNIQUE (user_id, date);
ALTER TABLE public.booking_event_types ADD CONSTRAINT booking_event_types_user_id_slug_key UNIQUE (user_id, slug);
ALTER TABLE public.business_holidays ADD CONSTRAINT business_holidays_organization_id_date_key UNIQUE (organization_id, date);
ALTER TABLE public.business_hours ADD CONSTRAINT business_hours_organization_id_key UNIQUE (organization_id);
ALTER TABLE public.cakto_recovery_config ADD CONSTRAINT cakto_recovery_config_organization_id_key UNIQUE (organization_id);
ALTER TABLE public.custom_fields ADD CONSTRAINT custom_fields_organization_id_field_key_key UNIQUE (organization_id, field_key);
ALTER TABLE public.distribution_config ADD CONSTRAINT distribution_config_squad_id_key UNIQUE (squad_id);
ALTER TABLE public.email_templates ADD CONSTRAINT email_templates_organization_id_slug_key UNIQUE (organization_id, slug);
ALTER TABLE public.email_unsubscribe_tokens ADD CONSTRAINT email_unsubscribe_tokens_email_key UNIQUE (email);
ALTER TABLE public.email_unsubscribe_tokens ADD CONSTRAINT email_unsubscribe_tokens_token_key UNIQUE (token);
ALTER TABLE public.forms ADD CONSTRAINT forms_organization_id_slug_key UNIQUE (organization_id, slug);
ALTER TABLE public.funnel_analytics ADD CONSTRAINT funnel_analytics_funnel_id_channel_date_key UNIQUE (funnel_id, channel, date);
ALTER TABLE public.google_calendar_connections ADD CONSTRAINT google_calendar_connections_user_id_key UNIQUE (user_id);
ALTER TABLE public.help_article_feedback ADD CONSTRAINT help_article_feedback_article_id_user_id_key UNIQUE (article_id, user_id);
ALTER TABLE public.help_articles ADD CONSTRAINT help_articles_slug_key UNIQUE (slug);
ALTER TABLE public.help_categories ADD CONSTRAINT help_categories_slug_key UNIQUE (slug);
ALTER TABLE public.hotmart_credentials ADD CONSTRAINT hotmart_credentials_organization_id_key UNIQUE (organization_id);
ALTER TABLE public.hotmart_orders ADD CONSTRAINT hotmart_orders_organization_id_transaction_id_event_type_key UNIQUE (organization_id, transaction_id, event_type);
ALTER TABLE public.hotmart_product_mapping ADD CONSTRAINT hotmart_product_mapping_organization_id_hotmart_product_id_key UNIQUE (organization_id, hotmart_product_id);
ALTER TABLE public.integration_settings ADD CONSTRAINT integration_settings_organization_id_integration_type_key UNIQUE (organization_id, integration_type);
ALTER TABLE public.lead_queue ADD CONSTRAINT lead_queue_lead_id_key UNIQUE (lead_id);
ALTER TABLE public.lead_tag_assignments ADD CONSTRAINT lead_tag_assignments_lead_tag_unique UNIQUE (lead_id, tag_id);
ALTER TABLE public.lead_tags ADD CONSTRAINT lead_tags_organization_id_name_key UNIQUE (organization_id, name);
ALTER TABLE public.notification_logs ADD CONSTRAINT notification_logs_user_id_notification_type_reference_id_re_key UNIQUE (user_id, notification_type, reference_id, reference_date);
ALTER TABLE public.org_ai_credentials ADD CONSTRAINT org_ai_credentials_organization_id_provider_key UNIQUE (organization_id, provider);
ALTER TABLE public.org_ai_routing ADD CONSTRAINT org_ai_routing_organization_id_capability_key UNIQUE (organization_id, capability);
ALTER TABLE public.organization_orchestrator_config ADD CONSTRAINT organization_orchestrator_config_organization_id_key UNIQUE (organization_id);
ALTER TABLE public.platform_email_templates ADD CONSTRAINT platform_email_templates_slug_key UNIQUE (slug);
ALTER TABLE public.platform_plans ADD CONSTRAINT platform_plans_slug_key UNIQUE (slug);
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_unique UNIQUE (organization_id, product_id, event_type);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_booking_slug_key UNIQUE (booking_slug);
ALTER TABLE public.sankhya_mappings ADD CONSTRAINT sankhya_mappings_organization_id_entity_type_local_id_key UNIQUE (organization_id, entity_type, local_id);
ALTER TABLE public.sector_members ADD CONSTRAINT sector_members_sector_id_user_id_key UNIQUE (sector_id, user_id);
ALTER TABLE public.sector_members ADD CONSTRAINT sector_members_sector_user_unique UNIQUE (sector_id, user_id);
ALTER TABLE public.sectors ADD CONSTRAINT sectors_organization_id_name_key UNIQUE (organization_id, name);
ALTER TABLE public.squad_members ADD CONSTRAINT squad_members_squad_id_user_id_key UNIQUE (squad_id, user_id);
ALTER TABLE public.stage_values ADD CONSTRAINT stage_values_stage_id_key UNIQUE (stage_id);
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_organization_id_key UNIQUE (organization_id);
ALTER TABLE public.suppressed_emails ADD CONSTRAINT suppressed_emails_email_key UNIQUE (email);
ALTER TABLE public.team_invitations ADD CONSTRAINT team_invitations_token_key UNIQUE (token);
ALTER TABLE public.user_availability ADD CONSTRAINT user_availability_user_id_day_of_week_start_time_key UNIQUE (user_id, day_of_week, start_time);
ALTER TABLE public.user_permissions ADD CONSTRAINT user_permissions_user_id_key UNIQUE (user_id);
ALTER TABLE public.user_product_assignments ADD CONSTRAINT user_product_assignments_user_id_product_id_key UNIQUE (user_id, product_id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE public.user_status ADD CONSTRAINT user_status_user_id_key UNIQUE (user_id);
ALTER TABLE public.webchat_conversations ADD CONSTRAINT unique_visitor_session UNIQUE (widget_id, visitor_id);

-- CHECK CONSTRAINTS
ALTER TABLE public.admin_agent_messages ADD CONSTRAINT admin_agent_messages_direction_check CHECK ((direction = ANY (ARRAY['outbound'::text, 'inbound'::text])));
ALTER TABLE public.admin_agent_messages ADD CONSTRAINT admin_agent_messages_message_type_check CHECK ((message_type = ANY (ARRAY['daily_summary'::text, 'weekly_report'::text, 'realtime_alert'::text, 'reactive'::text, 'test'::text])));
ALTER TABLE public.admin_notifications ADD CONSTRAINT admin_notifications_scope_check CHECK ((scope = ANY (ARRAY['all'::text, 'product'::text, 'squad'::text, 'custom'::text])));
ALTER TABLE public.agent_post_sale_scenarios ADD CONSTRAINT agent_post_sale_scenarios_trigger_event_check CHECK ((trigger_event = ANY (ARRAY['paid'::text, 'abandoned'::text, 'refunded'::text])));
ALTER TABLE public.agent_training_materials ADD CONSTRAINT agent_training_materials_category_check CHECK ((category = ANY (ARRAY['sales_techniques'::text, 'communication'::text, 'objections'::text, 'closing'::text, 'prospecting'::text, 'negotiation'::text, 'general'::text])));
ALTER TABLE public.agent_training_materials ADD CONSTRAINT agent_training_materials_material_type_check CHECK ((material_type = ANY (ARRAY['pdf'::text, 'video'::text, 'text'::text, 'website'::text])));
ALTER TABLE public.agent_training_materials ADD CONSTRAINT agent_training_materials_processing_status_check CHECK ((processing_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])));
ALTER TABLE public.ai_audits ADD CONSTRAINT ai_audits_quality_score_check CHECK (((quality_score >= 0) AND (quality_score <= 100)));
ALTER TABLE public.ai_outreach_queue ADD CONSTRAINT ai_outreach_queue_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'sent'::text, 'replied'::text, 'completed'::text, 'failed'::text])));
ALTER TABLE public.ai_response_feedback ADD CONSTRAINT ai_response_feedback_feedback_type_check CHECK ((feedback_type = ANY (ARRAY['correction'::text, 'tone'::text, 'accuracy'::text, 'content'::text])));
ALTER TABLE public.booking_event_types ADD CONSTRAINT booking_event_types_booking_experience_check CHECK ((booking_experience = ANY (ARRAY['standard'::text, 'conversational'::text])));
ALTER TABLE public.booking_requests ADD CONSTRAINT booking_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text])));
ALTER TABLE public.cakto_credentials ADD CONSTRAINT cakto_credentials_scope_check CHECK ((scope = ANY (ARRAY['platform'::text, 'organization'::text])));
ALTER TABLE public.cakto_credentials ADD CONSTRAINT cakto_creds_org_required CHECK ((((scope = 'platform'::text) AND (organization_id IS NULL)) OR ((scope = 'organization'::text) AND (organization_id IS NOT NULL))));
ALTER TABLE public.cakto_orders ADD CONSTRAINT cakto_orders_provider_check CHECK ((provider = ANY (ARRAY['cakto'::text, 'doppus'::text, 'hotmart'::text, 'kiwify'::text, 'manual'::text])));
ALTER TABLE public.cakto_orders ADD CONSTRAINT cakto_orders_scope_check CHECK ((scope = ANY (ARRAY['platform'::text, 'organization'::text])));
ALTER TABLE public.capture_funnels ADD CONSTRAINT capture_funnels_distribution_rule_check CHECK ((distribution_rule = ANY (ARRAY['manual'::text, 'round_robin'::text, 'squad'::text, 'user'::text])));
ALTER TABLE public.capture_funnels ADD CONSTRAINT capture_funnels_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'archived'::text])));
ALTER TABLE public.catalog_sync_logs ADD CONSTRAINT catalog_sync_logs_status_check CHECK ((status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])));
ALTER TABLE public.commission_rules ADD CONSTRAINT commission_rules_applies_to_check CHECK ((applies_to = ANY (ARRAY['deal'::text, 'stage'::text])));
ALTER TABLE public.commission_rules ADD CONSTRAINT commission_rules_rule_type_check CHECK ((rule_type = ANY (ARRAY['percentage'::text, 'fixed'::text])));
ALTER TABLE public.commissions ADD CONSTRAINT commissions_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'paid'::text, 'cancelled'::text])));
ALTER TABLE public.custom_fields ADD CONSTRAINT custom_fields_field_type_check CHECK ((field_type = ANY (ARRAY['text'::text, 'number'::text, 'select'::text, 'boolean'::text, 'date'::text])));
ALTER TABLE public.deals ADD CONSTRAINT deals_status_check CHECK ((status = ANY (ARRAY['won'::text, 'lost'::text, 'cancelled'::text])));
ALTER TABLE public.distribution_config ADD CONSTRAINT distribution_config_method_check CHECK ((method = ANY (ARRAY['round_robin'::text, 'least_busy'::text, 'performance'::text])));
ALTER TABLE public.email_send_log ADD CONSTRAINT email_send_log_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'sent'::text, 'suppressed'::text, 'failed'::text, 'bounced'::text, 'complained'::text, 'dlq'::text])));
ALTER TABLE public.email_send_state ADD CONSTRAINT email_send_state_id_check CHECK ((id = 1));
ALTER TABLE public.form_blocks ADD CONSTRAINT form_blocks_block_type_check CHECK ((block_type = ANY (ARRAY['text'::text, 'email'::text, 'phone'::text, 'number'::text, 'textarea'::text, 'select'::text, 'multi_select'::text, 'yes_no'::text, 'scale'::text, 'conditional'::text, 'score'::text, 'tag'::text, 'hidden_field'::text, 'ai_question'::text, 'ai_followup'::text, 'welcome_screen'::text, 'end_screen'::text])));
ALTER TABLE public.form_submissions ADD CONSTRAINT form_submissions_status_check CHECK ((status = ANY (ARRAY['started'::text, 'abandoned'::text, 'completed'::text])));
ALTER TABLE public.form_templates ADD CONSTRAINT form_templates_category_check CHECK ((category = ANY (ARRAY['general'::text, 'qualification'::text, 'diagnostic'::text, 'pre_sale'::text, 'feedback'::text, 'survey'::text])));
ALTER TABLE public.forms ADD CONSTRAINT forms_distribution_rule_check CHECK ((distribution_rule = ANY (ARRAY['manual'::text, 'round_robin'::text, 'squad'::text, 'user'::text])));
ALTER TABLE public.forms ADD CONSTRAINT forms_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'archived'::text])));
ALTER TABLE public.funnel_analytics ADD CONSTRAINT funnel_analytics_channel_check CHECK ((channel = ANY (ARRAY['chat'::text, 'form'::text, 'widget'::text])));
ALTER TABLE public.help_categories ADD CONSTRAINT help_categories_visibility_check CHECK ((visibility = ANY (ARRAY['all'::text, 'super_admin_only'::text])));
ALTER TABLE public.interactions ADD CONSTRAINT interactions_direction_check CHECK ((direction = ANY (ARRAY['inbound'::text, 'outbound'::text])));
ALTER TABLE public.lead_queue ADD CONSTRAINT lead_queue_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'assigned'::text, 'expired'::text])));
ALTER TABLE public.lead_tag_assignments ADD CONSTRAINT lead_tag_assignments_source_check CHECK ((source = ANY (ARRAY['manual'::text, 'flow'::text, 'ai_agent'::text, 'automation'::text, 'webhook'::text])));
ALTER TABLE public.message_reactions ADD CONSTRAINT message_reactions_check CHECK ((((reactor_type = 'agent'::text) AND (user_id IS NOT NULL) AND (visitor_id IS NULL)) OR ((reactor_type = 'visitor'::text) AND (visitor_id IS NOT NULL) AND (user_id IS NULL))));
ALTER TABLE public.message_reactions ADD CONSTRAINT message_reactions_reactor_type_check CHECK ((reactor_type = ANY (ARRAY['agent'::text, 'visitor'::text])));
ALTER TABLE public.org_ai_credentials ADD CONSTRAINT org_ai_credentials_provider_check CHECK ((provider = ANY (ARRAY['openai'::text, 'anthropic'::text, 'gemini'::text])));
ALTER TABLE public.org_ai_routing ADD CONSTRAINT org_ai_routing_capability_check CHECK ((capability = ANY (ARRAY['agent_chat'::text, 'sales_copilot'::text, 'audio_transcription'::text, 'image_vision'::text, 'content_generation'::text, 'analysis_insights'::text, 'embeddings'::text])));
ALTER TABLE public.org_ai_routing ADD CONSTRAINT org_ai_routing_provider_check CHECK ((provider = ANY (ARRAY['lovable'::text, 'openai'::text, 'anthropic'::text, 'gemini'::text])));
ALTER TABLE public.payment_links ADD CONSTRAINT payment_links_amount_check CHECK ((amount >= (0)::numeric));
ALTER TABLE public.payment_links ADD CONSTRAINT payment_links_status_check CHECK ((status = ANY (ARRAY['sent'::text, 'opened'::text, 'paid'::text, 'expired'::text, 'cancelled'::text])));
ALTER TABLE public.platform_email_templates ADD CONSTRAINT platform_email_templates_category_check CHECK ((category = ANY (ARRAY['acesso'::text, 'cobranca'::text, 'sistema'::text, 'mala_direta'::text])));
ALTER TABLE public.platform_settings ADD CONSTRAINT platform_settings_login_bg_layout_check CHECK ((login_bg_layout = ANY (ARRAY['fullscreen'::text, 'split-left'::text, 'split-right'::text])));
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_actions_deal_outcome_check CHECK ((deal_outcome = ANY (ARRAY['none'::text, 'won'::text, 'lost'::text])));
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_actions_deal_value_source_check CHECK ((deal_value_source = ANY (ARRAY['none'::text, 'webhook'::text, 'manual'::text])));
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_actions_message_channel_check CHECK ((message_channel = ANY (ARRAY['whatsapp'::text, 'email'::text])));
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_actions_send_mode_check CHECK ((send_mode = ANY (ARRAY['none'::text, 'flow'::text, 'message'::text])));
ALTER TABLE public.post_sale_event_actions ADD CONSTRAINT post_sale_event_actions_event_check CHECK ((event_type = ANY (ARRAY['compra_aprovada'::text, 'pix_gerado'::text, 'boleto_gerado'::text, 'carrinho_abandonado'::text, 'checkout_abandonado'::text, 'reembolso'::text, 'chargeback'::text, 'assinatura_cancelada'::text])));
ALTER TABLE public.product_agents ADD CONSTRAINT product_agents_quick_menu_mode_check CHECK ((quick_menu_mode = ANY (ARRAY['off'::text, 'always'::text, 'fallback'::text])));
ALTER TABLE public.product_catalog_items ADD CONSTRAINT product_catalog_items_source_type_check CHECK ((source_type = ANY (ARRAY['manual'::text, 'firecrawl'::text, 'webhook'::text, 'api'::text, 'csv'::text])));
ALTER TABLE public.product_ctas ADD CONSTRAINT product_ctas_cta_type_check CHECK ((cta_type = ANY (ARRAY['checkout'::text, 'whatsapp'::text, 'calendar'::text, 'callback'::text, 'video'::text, 'custom'::text])));
ALTER TABLE public.product_ctas ADD CONSTRAINT product_ctas_intent_level_check CHECK ((intent_level = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])));
ALTER TABLE public.product_knowledge_sources ADD CONSTRAINT product_knowledge_sources_processing_status_check CHECK (((processing_status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying])::text[])));
ALTER TABLE public.product_knowledge_sources ADD CONSTRAINT product_knowledge_sources_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['file'::character varying, 'website'::character varying, 'youtube'::character varying, 'faq'::character varying, 'data'::character varying, 'training'::character varying])::text[])));
ALTER TABLE public.product_offers ADD CONSTRAINT product_offers_role_check CHECK ((role = ANY (ARRAY['main'::text, 'front_end'::text, 'order_bump'::text, 'upsell'::text, 'downsell'::text, 'cross_sell'::text])));
ALTER TABLE public.stage_values ADD CONSTRAINT stage_values_probability_percent_check CHECK (((probability_percent >= (0)::numeric) AND (probability_percent <= (100)::numeric)));
ALTER TABLE public.support_messages ADD CONSTRAINT support_messages_author_role_check CHECK ((author_role = ANY (ARRAY['admin'::text, 'super_admin'::text])));
ALTER TABLE public.suppressed_emails ADD CONSTRAINT suppressed_emails_reason_check CHECK ((reason = ANY (ARRAY['unsubscribe'::text, 'bounce'::text, 'complaint'::text])));
ALTER TABLE public.tag_automations ADD CONSTRAINT tag_automations_event_type_check CHECK ((event_type = ANY (ARRAY['compra_aprovada'::text, 'pix_gerado'::text, 'boleto_gerado'::text, 'checkout_abandonado'::text, 'reembolso'::text, 'chargeback'::text, 'assinatura_cancelada'::text])));
ALTER TABLE public.team_invitations ADD CONSTRAINT team_invitations_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text, 'cancelled'::text])));
ALTER TABLE public.user_availability ADD CONSTRAINT user_availability_day_of_week_check CHECK (((day_of_week >= 0) AND (day_of_week <= 6)));
ALTER TABLE public.user_status ADD CONSTRAINT user_status_status_check CHECK ((status = ANY (ARRAY['online'::text, 'away'::text, 'offline'::text])));
ALTER TABLE public.webchat_assignment_events ADD CONSTRAINT webchat_assignment_events_action_check CHECK ((action = ANY (ARRAY['assigned'::text, 'unassigned'::text, 'transferred'::text, 'auto_assigned'::text])));
ALTER TABLE public.webchat_conversations ADD CONSTRAINT webchat_conversations_flow_source_check CHECK (((flow_source IS NULL) OR (flow_source = ANY (ARRAY['chat_flow'::text, 'funnel'::text, 'webhook_trigger'::text]))));
ALTER TABLE public.webchat_messages ADD CONSTRAINT webchat_messages_content_type_check CHECK ((content_type = ANY (ARRAY['text'::text, 'image'::text, 'file'::text, 'audio'::text])));
ALTER TABLE public.webchat_messages ADD CONSTRAINT webchat_messages_direction_check CHECK ((direction = ANY (ARRAY['inbound'::text, 'outbound'::text])));
ALTER TABLE public.webchat_messages ADD CONSTRAINT webchat_messages_sender_type_check CHECK ((sender_type = ANY (ARRAY['visitor'::text, 'bot'::text, 'agent'::text])));
ALTER TABLE public.webchat_widgets ADD CONSTRAINT webchat_widgets_position_check CHECK (("position" = ANY (ARRAY['bottom-right'::text, 'bottom-left'::text])));

-- INDEXES (excluding PK/Unique constraint indexes)
CREATE INDEX idx_admin_agent_messages_org_created ON public.admin_agent_messages USING btree (organization_id, created_at DESC);
CREATE INDEX idx_admin_agent_messages_org_type_ref ON public.admin_agent_messages USING btree (organization_id, message_type, reference_id, created_at DESC);
CREATE INDEX idx_admin_notifications_created_at ON public.admin_notifications USING btree (created_at DESC);
CREATE INDEX idx_admin_notifications_org ON public.admin_notifications USING btree (organization_id);
CREATE INDEX idx_agent_action_logs_agent ON public.agent_action_logs USING btree (agent_id);
CREATE INDEX idx_agent_action_logs_conversation ON public.agent_action_logs USING btree (conversation_id);
CREATE INDEX idx_agent_action_logs_created ON public.agent_action_logs USING btree (created_at DESC);
CREATE INDEX idx_agent_action_logs_lead ON public.agent_action_logs USING btree (lead_id);
CREATE INDEX idx_agent_activation_logs_org_created ON public.agent_activation_logs USING btree (organization_id, created_at DESC);
CREATE INDEX idx_agent_activation_logs_to_agent_created ON public.agent_activation_logs USING btree (to_agent_id, created_at DESC);
CREATE INDEX idx_agent_handoff_history_conv ON public.agent_handoff_history USING btree (conversation_id, created_at DESC);
CREATE INDEX idx_agent_handoff_history_lead ON public.agent_handoff_history USING btree (lead_id, created_at DESC);
CREATE INDEX idx_agent_handoff_history_org ON public.agent_handoff_history USING btree (organization_id, created_at DESC);
CREATE INDEX idx_post_sale_scenarios_org_event ON public.agent_post_sale_scenarios USING btree (organization_id, trigger_event, is_active, priority DESC);
CREATE INDEX idx_agent_routing_rules_org ON public.agent_routing_rules USING btree (organization_id, is_active, priority);
CREATE INDEX idx_agent_specialists_agent ON public.agent_specialists USING btree (agent_id);
CREATE INDEX idx_agent_specialists_org ON public.agent_specialists USING btree (organization_id);
CREATE INDEX idx_agent_specialists_role ON public.agent_specialists USING btree (role);
CREATE INDEX idx_agent_tool_exec_conv ON public.agent_tool_executions USING btree (conversation_id, created_at DESC);
CREATE INDEX idx_agent_tool_exec_lead ON public.agent_tool_executions USING btree (lead_id, created_at DESC);
CREATE INDEX idx_agent_tool_exec_org ON public.agent_tool_executions USING btree (organization_id, created_at DESC);
CREATE INDEX idx_agent_tool_exec_tool ON public.agent_tool_executions USING btree (tool_name, created_at DESC);
CREATE INDEX idx_training_materials_agent ON public.agent_training_materials USING btree (agent_id);
CREATE INDEX idx_training_materials_agent_active ON public.agent_training_materials USING btree (agent_id, is_active) WHERE (is_active = true);
CREATE INDEX idx_training_materials_product ON public.agent_training_materials USING btree (product_id);
CREATE INDEX idx_training_materials_product_active ON public.agent_training_materials USING btree (product_id, is_active) WHERE (is_active = true);
CREATE INDEX idx_ai_knowledge_base_category ON public.ai_knowledge_base USING btree (category);
CREATE INDEX idx_ai_knowledge_base_product ON public.ai_knowledge_base USING btree (product_id);
CREATE INDEX idx_ai_outreach_queue_followup ON public.ai_outreach_queue USING btree (next_followup_at) WHERE ((status = 'sent'::text) AND (followup_enabled = true));
CREATE INDEX idx_ai_outreach_queue_lead ON public.ai_outreach_queue USING btree (lead_id);
CREATE INDEX idx_ai_outreach_queue_org ON public.ai_outreach_queue USING btree (organization_id);
CREATE INDEX idx_ai_outreach_queue_status ON public.ai_outreach_queue USING btree (status);
CREATE INDEX idx_ai_experiments_agent ON public.ai_prompt_experiments USING btree (agent_id);
CREATE INDEX idx_ai_experiments_org ON public.ai_prompt_experiments USING btree (organization_id, status);
CREATE INDEX idx_ai_variants_exp ON public.ai_prompt_variants USING btree (experiment_id);
CREATE INDEX idx_ai_quality_agent ON public.ai_quality_evaluations USING btree (agent_id, created_at DESC);
CREATE INDEX idx_ai_quality_conv ON public.ai_quality_evaluations USING btree (conversation_id);
CREATE INDEX idx_ai_quality_org_created ON public.ai_quality_evaluations USING btree (organization_id, created_at DESC);
CREATE INDEX idx_ai_response_feedback_applied ON public.ai_response_feedback USING btree (applied_to_training);
CREATE INDEX idx_ai_response_feedback_conversation ON public.ai_response_feedback USING btree (conversation_id);
CREATE INDEX idx_ai_response_feedback_org ON public.ai_response_feedback USING btree (organization_id);
CREATE INDEX idx_ai_router_failures_org_created ON public.ai_router_failures USING btree (organization_id, created_at DESC);
CREATE INDEX idx_availability_overrides_user_date ON public.availability_overrides USING btree (user_id, date);
CREATE INDEX idx_booking_event_types_org ON public.booking_event_types USING btree (organization_id);
CREATE INDEX idx_booking_event_types_slug ON public.booking_event_types USING btree (slug);
CREATE INDEX idx_booking_event_types_user ON public.booking_event_types USING btree (user_id);
CREATE INDEX idx_booking_requests_event_type ON public.booking_requests USING btree (event_type_id);
CREATE INDEX idx_booking_requests_host ON public.booking_requests USING btree (host_user_id);
CREATE INDEX idx_booking_requests_start_time ON public.booking_requests USING btree (start_time);
CREATE INDEX idx_booking_requests_token ON public.booking_requests USING btree (confirmation_token);
CREATE INDEX idx_business_holidays_org_date ON public.business_holidays USING btree (organization_id, date);
CREATE UNIQUE INDEX cakto_credentials_org_unique ON public.cakto_credentials USING btree (organization_id) WHERE (scope = 'organization'::text);
CREATE UNIQUE INDEX cakto_credentials_platform_unique ON public.cakto_credentials USING btree (scope) WHERE (scope = 'platform'::text);
CREATE INDEX cakto_orders_lookup_idx ON public.cakto_orders USING btree (scope, organization_id, status, paid_at DESC);
CREATE UNIQUE INDEX cakto_orders_scope_org_cakto_id_key ON public.cakto_orders USING btree (scope, organization_id, cakto_id);
CREATE UNIQUE INDEX cakto_orders_unique_per_scope ON public.cakto_orders USING btree (scope, COALESCE(organization_id, '00000000-0000-0000-0000-000000000000'::uuid), cakto_id);
CREATE INDEX idx_cakto_orders_assigned_to ON public.cakto_orders USING btree (assigned_to);
CREATE INDEX idx_cakto_orders_items ON public.cakto_orders USING gin (items);
CREATE INDEX idx_cakto_orders_offer ON public.cakto_orders USING btree (offer_id);
CREATE INDEX idx_cakto_orders_product ON public.cakto_orders USING btree (product_id);
CREATE INDEX idx_cakto_orders_provider ON public.cakto_orders USING btree (organization_id, provider, paid_at DESC);
CREATE INDEX idx_recovery_dispatches_lead_event ON public.cakto_recovery_dispatches USING btree (lead_id, cakto_event, created_at DESC);
CREATE INDEX idx_recovery_dispatches_order ON public.cakto_recovery_dispatches USING btree (cakto_order_id);
CREATE INDEX idx_recovery_dispatches_org_created ON public.cakto_recovery_dispatches USING btree (organization_id, created_at DESC);
CREATE INDEX idx_calendar_events_google_event_id ON public.calendar_events USING btree (google_event_id) WHERE (google_event_id IS NOT NULL);
CREATE INDEX idx_calendar_events_google_id ON public.calendar_events USING btree (google_event_id);
CREATE INDEX idx_calendar_events_lead_id ON public.calendar_events USING btree (lead_id);
CREATE INDEX idx_calendar_events_org_id ON public.calendar_events USING btree (organization_id);
CREATE INDEX idx_calendar_events_start_time ON public.calendar_events USING btree (start_time);
CREATE INDEX idx_calendar_events_user_id ON public.calendar_events USING btree (user_id);
CREATE UNIQUE INDEX capture_funnels_org_slug_idx ON public.capture_funnels USING btree (organization_id, slug);
CREATE INDEX capture_funnels_organization_idx ON public.capture_funnels USING btree (organization_id);
CREATE INDEX capture_funnels_product_idx ON public.capture_funnels USING btree (product_id);
CREATE INDEX capture_funnels_status_idx ON public.capture_funnels USING btree (status);
CREATE INDEX catalog_sync_logs_org_product_idx ON public.catalog_sync_logs USING btree (organization_id, product_id, started_at DESC);
CREATE INDEX idx_chat_flows_org_active ON public.chat_flows USING btree (organization_id, is_active);
CREATE INDEX idx_chat_flows_product ON public.chat_flows USING btree (product_id);
CREATE INDEX idx_conversation_notes_conv ON public.conversation_notes USING btree (conversation_id);
CREATE INDEX idx_conversation_transfers_conv ON public.conversation_transfers USING btree (conversation_id);
CREATE INDEX idx_email_send_log_created ON public.email_send_log USING btree (created_at DESC);
CREATE INDEX idx_email_send_log_message ON public.email_send_log USING btree (message_id);
CREATE UNIQUE INDEX idx_email_send_log_message_sent_unique ON public.email_send_log USING btree (message_id) WHERE (status = 'sent'::text);
CREATE INDEX idx_email_send_log_recipient ON public.email_send_log USING btree (recipient_email);
CREATE INDEX idx_unsubscribe_tokens_token ON public.email_unsubscribe_tokens USING btree (token);
CREATE INDEX idx_evolution_instances_instance_id ON public.evolution_instances USING btree (instance_id);
CREATE UNIQUE INDEX idx_evolution_instances_one_default ON public.evolution_instances USING btree (organization_id) WHERE (is_default = true);
CREATE INDEX idx_evolution_instances_org ON public.evolution_instances USING btree (organization_id);
CREATE INDEX idx_fb_integrations_org ON public.facebook_lead_integrations USING btree (organization_id);
CREATE INDEX idx_fb_integrations_page ON public.facebook_lead_integrations USING btree (page_id);
CREATE INDEX idx_fb_integrations_product ON public.facebook_lead_integrations USING btree (product_id);
CREATE INDEX idx_fb_logs_integration ON public.facebook_lead_logs USING btree (integration_id);
CREATE INDEX idx_fb_logs_leadgen ON public.facebook_lead_logs USING btree (leadgen_id);
CREATE INDEX idx_fb_logs_status ON public.facebook_lead_logs USING btree (status);
CREATE INDEX idx_form_blocks_form ON public.form_blocks USING btree (form_id);
CREATE INDEX idx_form_blocks_order ON public.form_blocks USING btree (form_id, order_index);
CREATE INDEX idx_form_submissions_created ON public.form_submissions USING btree (created_at DESC);
CREATE INDEX idx_form_submissions_form ON public.form_submissions USING btree (form_id);
CREATE INDEX idx_form_submissions_lead ON public.form_submissions USING btree (lead_id);
CREATE INDEX idx_form_submissions_status ON public.form_submissions USING btree (status);
CREATE INDEX idx_form_templates_category ON public.form_templates USING btree (category);
CREATE INDEX idx_form_templates_org ON public.form_templates USING btree (organization_id);
CREATE INDEX idx_forms_organization ON public.forms USING btree (organization_id);
CREATE INDEX idx_forms_product ON public.forms USING btree (product_id);
CREATE INDEX idx_forms_slug ON public.forms USING btree (slug);
CREATE INDEX idx_forms_status ON public.forms USING btree (status);
CREATE INDEX funnel_analytics_channel_idx ON public.funnel_analytics USING btree (channel);
CREATE INDEX funnel_analytics_date_idx ON public.funnel_analytics USING btree (date);
CREATE INDEX funnel_analytics_funnel_idx ON public.funnel_analytics USING btree (funnel_id);
CREATE INDEX idx_funnel_webhook_logs_block ON public.funnel_webhook_logs USING btree (funnel_id, block_id, created_at DESC);
CREATE INDEX idx_funnel_webhook_logs_funnel ON public.funnel_webhook_logs USING btree (funnel_id, created_at DESC);
CREATE INDEX idx_funnel_webhook_logs_org ON public.funnel_webhook_logs USING btree (organization_id, created_at DESC);
CREATE INDEX idx_help_articles_category ON public.help_articles USING btree (category_id) WHERE (is_published = true);
CREATE INDEX idx_help_articles_published ON public.help_articles USING btree (is_published, published_at DESC);
CREATE INDEX idx_help_articles_tags ON public.help_articles USING gin (tags);
CREATE INDEX idx_hotmart_orders_buyer_email ON public.hotmart_orders USING btree (organization_id, buyer_email);
CREATE INDEX idx_hotmart_orders_created ON public.hotmart_orders USING btree (created_at_hotmart DESC);
CREATE INDEX idx_hotmart_orders_org ON public.hotmart_orders USING btree (organization_id);
CREATE INDEX idx_hotmart_orders_product ON public.hotmart_orders USING btree (product_id);
CREATE INDEX idx_hotmart_orders_status ON public.hotmart_orders USING btree (organization_id, status);
CREATE INDEX idx_lead_notes_author_id ON public.lead_notes USING btree (author_id);
CREATE INDEX idx_lead_notes_lead_id ON public.lead_notes USING btree (lead_id);
CREATE INDEX idx_lead_semantic_memory_created ON public.lead_semantic_memory USING btree (created_at DESC);
CREATE INDEX idx_lead_semantic_memory_embedding ON public.lead_semantic_memory USING hnsw (embedding vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_lead_semantic_memory_lead ON public.lead_semantic_memory USING btree (lead_id);
CREATE INDEX idx_lead_semantic_memory_org ON public.lead_semantic_memory USING btree (organization_id);
CREATE INDEX idx_lead_tag_assignments_lead ON public.lead_tag_assignments USING btree (lead_id);
CREATE INDEX idx_lead_tag_assignments_tag ON public.lead_tag_assignments USING btree (tag_id);
CREATE INDEX idx_lead_tags_org ON public.lead_tags USING btree (organization_id);
CREATE INDEX idx_lead_transfer_history_lead_id ON public.lead_transfer_history USING btree (lead_id);
CREATE INDEX idx_leads_assigned_to ON public.leads USING btree (assigned_to);
CREATE INDEX idx_leads_closer_id ON public.leads USING btree (closer_id);
CREATE INDEX idx_leads_lead_origin ON public.leads USING btree (lead_origin);
CREATE INDEX idx_leads_product_stage ON public.leads USING btree (product_id, current_stage_id);
CREATE INDEX idx_leads_sdr_id ON public.leads USING btree (sdr_id);
CREATE INDEX idx_leads_sector ON public.leads USING btree (sector_id);
CREATE INDEX idx_leads_squad_id ON public.leads USING btree (squad_id);
CREATE INDEX idx_leads_stage_value ON public.leads USING btree (current_stage_id, deal_value);
CREATE INDEX idx_leads_utm_source ON public.leads USING btree (utm_source);
CREATE UNIQUE INDEX leads_org_phone_unique ON public.leads USING btree (organization_id, phone_normalized) WHERE ((phone_normalized IS NOT NULL) AND (phone_normalized <> ''::text));
CREATE INDEX idx_message_reactions_conversation ON public.message_reactions USING btree (conversation_id);
CREATE INDEX idx_message_reactions_message ON public.message_reactions USING btree (message_id);
CREATE UNIQUE INDEX idx_message_reactions_unique_agent ON public.message_reactions USING btree (message_id, user_id) WHERE (user_id IS NOT NULL);
CREATE UNIQUE INDEX idx_message_reactions_unique_visitor ON public.message_reactions USING btree (message_id, visitor_id) WHERE (visitor_id IS NOT NULL);
CREATE INDEX idx_notification_logs_date ON public.notification_logs USING btree (reference_date);
CREATE INDEX idx_notification_logs_type ON public.notification_logs USING btree (notification_type);
CREATE INDEX idx_notification_logs_user ON public.notification_logs USING btree (user_id);
CREATE INDEX idx_notifications_admin_notification_id ON public.notifications USING btree (admin_notification_id);
CREATE INDEX idx_orchestration_logs_conversation ON public.orchestration_logs USING btree (conversation_id, created_at DESC);
CREATE INDEX idx_orchestration_logs_org_created ON public.orchestration_logs USING btree (organization_id, created_at DESC);
CREATE INDEX idx_payment_links_conv ON public.payment_links USING btree (conversation_id);
CREATE INDEX idx_payment_links_lead ON public.payment_links USING btree (lead_id);
CREATE INDEX idx_payment_links_org ON public.payment_links USING btree (organization_id, created_at DESC);
CREATE INDEX idx_platform_plans_active ON public.platform_plans USING btree (is_active, display_order);
CREATE INDEX idx_platform_release_reads_user ON public.platform_release_reads USING btree (user_id);
CREATE INDEX idx_platform_releases_published ON public.platform_releases USING btree (is_published, published_at DESC);
CREATE INDEX idx_post_sale_actions_org_event ON public.post_sale_event_actions USING btree (organization_id, event_type) WHERE (is_active = true);
CREATE INDEX idx_post_sale_actions_product ON public.post_sale_event_actions USING btree (product_id, event_type) WHERE (is_active = true);
CREATE INDEX idx_post_sale_logs_lead ON public.post_sale_event_logs USING btree (lead_id, created_at DESC);
CREATE INDEX idx_post_sale_logs_org_created ON public.post_sale_event_logs USING btree (organization_id, created_at DESC);
CREATE INDEX idx_product_agents_activation_priority ON public.product_agents USING btree (product_id, is_active, activation_priority DESC);
CREATE INDEX idx_product_agents_active ON public.product_agents USING btree (is_active);
CREATE INDEX idx_product_agents_evolution_instance ON public.product_agents USING btree (evolution_instance_id);
CREATE INDEX idx_product_agents_org ON public.product_agents USING btree (organization_id);
CREATE INDEX idx_product_agents_product ON public.product_agents USING btree (product_id);
CREATE INDEX idx_product_agents_type ON public.product_agents USING btree (agent_type);
CREATE INDEX product_catalog_items_attributes_idx ON public.product_catalog_items USING gin (attributes);
CREATE INDEX product_catalog_items_description_trgm_idx ON public.product_catalog_items USING gin (description gin_trgm_ops);
CREATE UNIQUE INDEX product_catalog_items_org_external_unique ON public.product_catalog_items USING btree (organization_id, COALESCE(product_id, '00000000-0000-0000-0000-000000000000'::uuid), external_id) WHERE (external_id IS NOT NULL);
CREATE INDEX product_catalog_items_org_product_active_price_idx ON public.product_catalog_items USING btree (organization_id, product_id, is_active, price);
CREATE INDEX product_catalog_items_search_idx ON public.product_catalog_items USING gin (search_vector);
CREATE INDEX product_catalog_items_tags_idx ON public.product_catalog_items USING gin (tags);
CREATE INDEX product_catalog_items_title_trgm_idx ON public.product_catalog_items USING gin (title gin_trgm_ops);
CREATE INDEX idx_product_ctas_organization_id ON public.product_ctas USING btree (organization_id);
CREATE INDEX idx_product_ctas_product_id ON public.product_ctas USING btree (product_id);
CREATE INDEX idx_product_offers_org ON public.product_offers USING btree (organization_id);
CREATE INDEX idx_product_offers_product ON public.product_offers USING btree (product_id);
CREATE UNIQUE INDEX uq_product_offers_cakto_per_org ON public.product_offers USING btree (organization_id, cakto_product_id) WHERE (cakto_product_id IS NOT NULL);
CREATE INDEX idx_product_suites_org ON public.product_suites USING btree (organization_id);
CREATE INDEX idx_product_training_videos_org ON public.product_training_videos USING btree (organization_id);
CREATE INDEX idx_product_training_videos_product ON public.product_training_videos USING btree (product_id);
CREATE INDEX idx_products_suite ON public.products USING btree (suite_id);
CREATE INDEX idx_quick_replies_category ON public.quick_replies USING btree (category);
CREATE INDEX idx_quick_replies_org ON public.quick_replies USING btree (organization_id);
CREATE INDEX idx_sankhya_mappings_local_id ON public.sankhya_mappings USING btree (local_id);
CREATE INDEX idx_sankhya_mappings_org_entity ON public.sankhya_mappings USING btree (organization_id, entity_type);
CREATE INDEX idx_sankhya_sync_logs_org ON public.sankhya_sync_logs USING btree (organization_id, started_at DESC);
CREATE INDEX idx_sector_members_sector ON public.sector_members USING btree (sector_id);
CREATE INDEX idx_sector_members_user ON public.sector_members USING btree (user_id);
CREATE INDEX idx_sectors_active ON public.sectors USING btree (organization_id, is_active);
CREATE INDEX idx_sectors_org ON public.sectors USING btree (organization_id);
CREATE UNIQUE INDEX sectors_one_default_per_org ON public.sectors USING btree (organization_id) WHERE (is_default = true);
CREATE INDEX idx_support_messages_ticket ON public.support_messages USING btree (ticket_id, created_at);
CREATE INDEX idx_support_tickets_org ON public.support_tickets USING btree (organization_id);
CREATE INDEX idx_support_tickets_status ON public.support_tickets USING btree (status);
CREATE INDEX idx_support_tickets_unread_sa ON public.support_tickets USING btree (unread_for_super_admin) WHERE (unread_for_super_admin = true);
CREATE INDEX idx_suppressed_emails_email ON public.suppressed_emails USING btree (email);
CREATE INDEX idx_tag_automations_org_event ON public.tag_automations USING btree (organization_id, event_type) WHERE (is_active = true);
CREATE INDEX idx_team_invitations_email ON public.team_invitations USING btree (email);
CREATE INDEX idx_team_invitations_organization ON public.team_invitations USING btree (organization_id);
CREATE INDEX idx_team_invitations_token ON public.team_invitations USING btree (token);
CREATE INDEX idx_user_availability_user ON public.user_availability USING btree (user_id);
CREATE INDEX idx_webchat_agent_configs_org ON public.webchat_agent_configs USING btree (organization_id);
CREATE INDEX idx_webchat_agent_configs_widget ON public.webchat_agent_configs USING btree (widget_id);
CREATE INDEX idx_webchat_conv_needs_human ON public.webchat_conversations USING btree (organization_id, needs_human) WHERE (needs_human = true);
CREATE INDEX idx_webchat_conv_org_lastmsg ON public.webchat_conversations USING btree (organization_id, last_message_at DESC NULLS LAST);
CREATE INDEX idx_webchat_conv_org_lead ON public.webchat_conversations USING btree (organization_id, lead_id);
CREATE INDEX idx_webchat_conv_org_status_lastmsg ON public.webchat_conversations USING btree (organization_id, status, last_message_at DESC NULLS LAST);
CREATE INDEX idx_webchat_conversations_agent ON public.webchat_conversations USING btree (current_agent_id);
CREATE INDEX idx_webchat_conversations_assigned ON public.webchat_conversations USING btree (assigned_user_id);
CREATE INDEX idx_webchat_conversations_evolution_instance ON public.webchat_conversations USING btree (evolution_instance_id);
CREATE INDEX idx_webchat_conversations_flow ON public.webchat_conversations USING btree (current_flow_id) WHERE (current_flow_id IS NOT NULL);
CREATE INDEX idx_webchat_conversations_lead ON public.webchat_conversations USING btree (lead_id);
CREATE INDEX idx_webchat_conversations_org ON public.webchat_conversations USING btree (organization_id);
CREATE INDEX idx_webchat_conversations_product ON public.webchat_conversations USING btree (product_id);
CREATE INDEX idx_webchat_conversations_sector ON public.webchat_conversations USING btree (sector_id);
CREATE INDEX idx_webchat_conversations_status ON public.webchat_conversations USING btree (status);
CREATE INDEX idx_webchat_conversations_visitor ON public.webchat_conversations USING btree (visitor_id);
CREATE INDEX idx_webchat_conversations_widget ON public.webchat_conversations USING btree (widget_id);
CREATE INDEX idx_webchat_messages_conversation ON public.webchat_messages USING btree (conversation_id);
CREATE INDEX idx_webchat_messages_created ON public.webchat_messages USING btree (created_at);
CREATE INDEX idx_webchat_widgets_org ON public.webchat_widgets USING btree (organization_id);
CREATE INDEX idx_webchat_widgets_product_id ON public.webchat_widgets USING btree (product_id);
CREATE UNIQUE INDEX webchat_widgets_product_unique ON public.webchat_widgets USING btree (product_id) WHERE (product_id IS NOT NULL);
CREATE INDEX idx_webhook_logs_created ON public.webhook_logs USING btree (created_at DESC);
CREATE INDEX idx_webhook_logs_status ON public.webhook_logs USING btree (status);
CREATE INDEX idx_webhook_logs_webhook ON public.webhook_logs USING btree (webhook_id);
CREATE INDEX idx_webhook_samples_webhook ON public.webhook_sample_requests USING btree (webhook_id);
CREATE INDEX idx_webhooks_org ON public.webhooks USING btree (organization_id);
CREATE UNIQUE INDEX idx_webhooks_org_slug ON public.webhooks USING btree (organization_id, slug);
